### ISSUE TITLE
[debops.dhcpd] Seemingly unrelated AnsibleUndefinedVariable errors

### ISSUE THREAD

**Issue by imrejonk** [debops/debops#1018]
Tested with:
Python 3.7.3 and 2.7.16
Ansible v2.7.13
Debops v1.0.7

I'm getting errors like these when running `debops.dhcpd`:

```
TASK [debops.dhcpd : Configure DHCP server] *************************************************************
ok: [orbit.gwl.amsw.nl] => (item=etc/default/isc-dhcp-server)
failed: [orbit.gwl.amsw.nl] (item=etc/dhcp/dhcpd.conf) => changed=false 
  item: etc/dhcp/dhcpd.conf
  msg: 'AnsibleUndefinedVariable: ''postfix__fqdn'' is undefined'
```

It looks like [the dhcpd.conf template](https://github.com/debops/debops/blob/master/ansible/roles/debops.dhcpd/templates/etc/dhcp/dhcpd.conf.j2) somehow tries to include all host and group variables and then fails to template some variables that are set from other role defaults.

My `debops.dhcpd` configuration is split into two files:

**ansible/inventory/group_vars/gwl/dhcpd.yml**
```
---
dhcpd_authoritative: True
dhcpd_global_default_lease_time: '7200'
dhcpd_global_max_lease_time: '7200'
dhcpd_nameservers: [ '194.109.6.66', '194.109.9.99', '194.109.104.104' ]

dhcpd_keys:

  - key: 'gwl'
    algorithm: 'hmac-sha256'
    secret: '{{ lookup("password", secret + "/dhcpd/tsig-keys/gwl") }}'

dhcpd_zones:

  - zone: 'gwl.amsw.nl'
    primary: '94.142.244.11'
    key: 'gwl'

  - zone: '7.205.10.in-addr.arpa'
    primary: '94.142.244.11'
    key: 'gwl'

dhcpd_subnets:

  - subnet: '10.205.7.0'
    netmask: '255.255.255.128'
    routers: [ '10.205.7.1' ]

    pools:

      - range: '10.205.7.10 10.205.7.62'

dhcpd_options: |
  ddns-update-style standard;
  ddns-domainname "gwl.amsw.nl";
```

**ansible/inventory/host_vars/orbit.gwl.amsw.nl/dhcpd.yml**
```
---
dhcpd_interfaces: [ 'br0' ]
```

**Comment by drybjed** [comment]
This is an issue with the `import` keyword in Jinja inside loops. I'll move the `macros.j2` contents into the `dhcpd.conf.j2` template, that should fix the issue. Thanks for spotting it.

**Comment by imrejonk** [comment]
Hi @drybjed, thanks for your work on fixing this issue. Unfortunately I'm seeing the same result after applying your patch. It's the same when I modify the 'Configure DHCP server' task and split the loop into two tasks like this:

```
- name: Configure DHCP server init options
  template:
    src: 'etc/default/isc-dhcp-server.j2'
    dest: '/etc/default/isc-dhcp-server'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart dhcp server' ]
  register: dhcpd_register_config
  when: dhcpd_mode == 'server'

- name: Configure DHCP server
  template:
    src: 'etc/dhcp/dhcpd.conf.j2'
    dest: '/etc/dhcp/dhcpd.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart dhcp server' ]
  register: dhcpd_register_config
  when: dhcpd_mode == 'server'
```

Could it be something else?
