### ISSUE TITLE
[debops.nginx] type proxy servers still create webroot even if set False

### ISSUE THREAD

**Issue by thiras** [debops/debops#1136]
Hello.

Here is my config;

```yaml
  - name: [ "voting.example.org" ]
    acme: True
    type: proxy
    webroot_create: False
    proxy_pass: "http://localhost:3000"
    proxy_headers: |-
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;

  - name: [ "data.example.org" ]
    acme: True
    type: proxy
    webroot_create: False
    proxy_pass: "http://localhost:19999"
    proxy_headers: |-
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    auth_basic: True
    auth_basic_name: "netdata"
```

Even `webroot_create` is set to `False`, it still creates webroots for those servers.
