### ISSUE TITLE
[debops.ferm] role keeps removing debops.avahi firewall rule

### ISSUE THREAD

**Issue by imrejonk** [debops/debops#1183]
The avahi playbook runs the debops.ferm role with these `ferm__dependent_rules`:
```
  - name: 'avahi'
    type: 'accept'
    dport: 'mdns'
    saddr: '{{ avahi__allow }}'
    protocol: 'udp'
    accept_any: True
    rule_state: '{{ "present" if (avahi__enabled|bool) else "absent" }}'
```
Without any variables overriding the role defaults, this renders `/etc/ferm/rules.d/100_rule_avahi.conf` as follows:
```
# This file is managed remotely, all changes will be lost

domain (ip ip6) table filter chain INPUT {
    protocol udp dport mdns {
        ACCEPT;
    }
}
```
Which seems fine. However, the rule gets removed when running the debops.ferm role again, but without the `ferm__dependent_rules` variable as shown above:
```
TASK [debops.ferm : Remove firewall rules] **************************************************************
--- before
+++ after
@@ -1,4 +1,4 @@
 {
     "path": "/etc/ferm/rules.d/100_rule_avahi.conf",
-    "state": "file"
+    "state": "absent"
 }

changed: [pancake.gwl.amsw.nl] => (item={'key': 'avahi', 'value': {'accept_any': True, 'dport': 'mdns', 'name': 'avahi', 'protocol': 'udp', 'rule_state': 'absent', 'rules': [{'accept_any': True, 'dport': 'mdns', 'protocol': 'udp', 'saddr': [], 'type': 'accept'}], 'saddr': [], 'type': 'accept'}})
[...]
```
The `debops.ferm` role should not remove earlier defined dependent rules. It is unclear to me why this only seems to happen with the `debops.avahi` rule.

## System information

- DebOps v1.2.0
- Python 3.7
- Debian 10

**Comment by tallandtree** [comment]
This also happens with other playbooks. I experience the same with docker_server and a custom playbook that both use ferm__dependent_rules and run ferm. Depending on which playbook is run last, the ferm rules of the first are removed. I think it is due to the task: "Remove unknown firewall rules" when running another playbook that adds ferm rules.

**Comment by drybjed** [comment]
I tried to reproduce this issue with Avahi, but in my development environment the `ferm` role does not remove the `avahi` rule when it is configured. The "Remove unknown firewall rules" was designed with multiple dependencies in mind - it only removes duplicate rules with different "weight" numbers to allow rule reordering.

@imrejonk Perhaps we could schedule a session over remote desktop where I could check out your environment and try debugging this?

**Comment by tallandtree** [comment]
@drybjed, you are right. In my case it happened due to an error in my variable. So, I've solved it.

**Comment by imrejonk** [comment]
@tallandtree what was the error, if I may ask? I'm probably doing something wrong in my inventory as well. I'll see if I can still reproduce this issue with Ansible 2.9 and a recent DebOps release.

**Comment by tallandtree** [comment]
@imrejonk I had chosen an incorrect `name`. So example in my custom role myapp/default/main.yml I had configured the following:
```
myapp__ferm_dependent_rules:
  type: 'accept'
  weight: '50'
  role: 'myapp-role'
  name: 'service_rule'
  dport: '4567'
  protocol: 'tcp'
  saddr: '10.100.10.100'
```
The name was a duplicate of the name used in the docker_service role, hence it was removed if I ran the docker_service role after my custom role. Or if I ran the myapp role after the docker_service role, the rule for docker_service was removed.
When I change `name: 'myapp_rule'`, both rules were kept. 

Hope this helps you too.

**Comment by imrejonk** [comment]
Well this is interesting. Renaming the dependent rule 'avahi' to something else ('avahi_test' below) solves the issue for me:

```
avahi__ferm__dependent_rules:

  - name: 'avahi_test'
    type: 'accept'
    dport: 'mdns'
    saddr: '{{ avahi__allow }}'
    protocol: 'udp'
    accept_any: True
    rule_state: '{{ "present" if (avahi__enabled|bool) else "absent" }}'
```

Running the `ferm` playbook afterwards no longer removes the avahi rule (`100_rule_avahi_test.conf`). There are no duplicate rules in `/etc/ferm/rules.d` as far as I can tell. What do we make of this?

**Comment by drybjed** [comment]
Well, let's see... There's [an `avahi` rule in the `ferm` role itself](https://github.com/debops/debops/blob/master/ansible/roles/ferm/defaults/main.yml#L524-L540) - it was added to allow for access to mDNS on hosts which have Avahi installed by default (think Ubuntu). The `avahi` role is not applied by default, but the `nsswitch` role is - with this, the `ferm` role can "decide" to allow mDNS traffic. The rule is designed to work with the `avahi` role present; meaning that it should not enable/disable Avahi access in a loop.

One other place that can have an eefect on the `ferm` rules is the Ansible inventory. Do you have any rules or variables that touch the `ferm` configuration? Perhaps you could try it in a completely new environment with clean inventory and see if the effect shows up again?

One more thing - the DebOps roles were recently renamed, the `debops.` prefix was dropped. Perhaps you have an `avahi` role that masks the one included in DebOps? The effects would manifest a bit more exremely if that role was completely different (no required variables present), but perhaps you took a DebOps role and modified it for some reason? I would check in that direction as well.

**Comment by imrejonk** [comment]
Found it :)
Was quite hard to reproduce this in Vagrant though, as the issue is only present on IPv6-enabled systems.

**Comment by FrankyFire** [comment]
It seems like this issue is still present in some way. I'm trying to use the debops zabbix-agent role to configure the agents and ferm rules for the clients. The installation and configuration works fine, but when the ferm rules are installed, I get:
```
TASK [debops.debops.ferm : Generate firewall rules] ******************************************************************************************
changed: [lc01s-dev] => (item=zabbix_agent_allow)

TASK [debops.debops.ferm : Remove unknown firewall rules] ************************************************************************************
changed: [lc01s-dev] => (item=zabbix_agent_allow)
```

My setup is pretty basic. In the hosts.yml I created the group debops_service_zabbix_agent. In the group_vars, I added a file with the same name and added some configuration including:

```
zabbix_agent__ferm__dependent_rules:
  - name: 'zabbix_agent_allow'
    type: 'accept'
    dport: [ 'zabbix-agent' ]
    protocol: [ 'tcp', 'udp' ]
    saddr: '{{ zabbix_agent__allow + zabbix_agent__group_allow + zabbix_agent__host_allow }}'
    weight: '50'
    by_role: 'debops.zabbix_agent'
    rule_state: '{{ zabbix_agent__deploy_state }}'
```

The playbook is taken directly from the official documentation and only one playbook is being imported in the end (which doesn't work either by the way).

```
- name: Install and manage Zabbix agent
  collections: [ 'debops.debops', 'debops.roles01',
                 'debops.roles02', 'debops.roles03' ]
  hosts: [ 'debops_service_zabbix_agent' ]
  become: True
  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'
  roles:
    - role: ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ zabbix_agent__ferm__dependent_rules }}'
    - role: zabbix_agent
      tags: [ 'role::zabbix_agent', 'skip::zabbix_agent' ]

- import_playbook: zabbix-api-fact-update.yml
```

That last playbook would just update the Zabbix Server, but again, it doesn't run for some other reason.
What am I doing wrong? Or is there another bug?

```
$ debops --version
debops 3.1.0
```

Edit:
Ignore that comment. There was an issue that Zabbix was unable to connect to that agent, but the line I pasted was just misguiding. The rule was in place (you can look that up in /etc/ferm/rules.d) and everything worked as expected. Just that message was misleading.
Sadly I don't know the cause for the problem, but a restart fixed it.
