### ISSUE TITLE
RFC: Support subpath/subdir hosting for additional security

### ISSUE THREAD

**Issue by ypid** [debops/debops#1233]
With the last three services that I deployed (searx, Vaultwarden and EteSync) I started thinking/worrying because I was required to expose those services on the open internet and with that basically everybody could talk to their API. The services are easy to find because they obviously use HTTPS (think about CT logs). Now this exposes quite a bit of attack surface. For other services, I would have reduced that by client certificates, firewalling or VPN. All of this was not feasible here so I came up with misusing the "sub dir/path deployment schema" (ref: https://docs.nextcloud.com/server/15/admin_manual/installation/nginx.html#nextcloud-in-a-subdir-of-nginx) for this.

The idea is to host services on https://etesync.example.org/JZ27jIoxLKxB6mu09eirMPc instead of just https://etesync.example.org/. It depends on the application of how much this is distracting for the user but for Vaultwarden and EteSync it works fine because during normal usage, the URLs are not visible to the end user.

~~Also for other services like Nextcloud this could be done. Maybe with a shorter "PSK" because there it will be visible to the end user.~~ After looking into it I consider it not worth the hassle because for Nextcloud, I would need to break the `/.well-known` URIs. Without breaking those URIs, the access control would be useless. Ref: https://docs.nextcloud.com/server/21/admin_manual/installation/nginx.html#nextcloud-in-a-subdir-of-the-nginx-webroot

~~Maybe even https://etesync.example.org/JZ27jIoxLKxB6mu09eirMPc_psk could be used to give a hint what it is about.~~ Decided against this. The PSK acronym probably does not mean much to the average user.

The reason I think we could do this is that nowadays, bookmarks and browser auto complete is so common that what in the old days used to be done by humans is now offloaded to machines thus the URL does not have to be remembered for my taste. It is still in the estimation of the admin to weight up security vs. usability.

Implementation would be done by Nginx so it is very easy to audit. The application only gets the request if the requester knows the PSK.

Example implementation:

```YAML
# .. envvar:: etesync__http_subpath [[[
#
# Deploy EteSync on a random subpath that acts as a protection of the web app
# from people not knowing this PSK.
etesync__http_subpath: '{{ lookup("password", secret + "/etesync/" +
                           inventory_hostname + "/config/subpath chars=ascii_letters,digits length=23") }}'

                                                                   # ]]]

# .. envvar:: etesync__nginx__dependent_servers [[[
#
# Server configuration for the :ref:`debops.nginx` Ansible role.
etesync__nginx__dependent_servers:
  - name: '{{ etesync__fqdn }}'
    by_role: 'debops.etesync'
    filename: 'debops.etesync'
    favicon: False
    http_referrer_policy: 'same-origin'
    options: |
      client_max_body_size {{ etesync__max_file_size }}M;

    location_list:

      - pattern: '/'
        options: |-
          deny all;

      ## EteSync Nginx config truncated.
      - pattern: '/{{ etesync__http_subpath }}'
        options: |-
          proxy_pass http://etesync;
          proxy_set_header X-Forwarded-Host $server_name;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Script-Name /{{ etesync__http_subpath }};
          proxy_connect_timeout {{ etesync__app_timeout }};
          proxy_send_timeout {{ etesync__app_timeout }};
          proxy_read_timeout {{ etesync__app_timeout }};
# ]]]
```

The "deny all" should probably be changed to be more user friendly.

Related to: https://github.com/debops/debops/issues/1194
