### ISSUE TITLE
ifupdown role breaks with current implementation of "auto"

### ISSUE THREAD

**Issue by rochecompaan** [debops/debops#1346]
First, thank you for an awesome project! It is really well thought out and well documented given the scope that you are trying to cover.

I have used quite a few roles successfully now. However, I ran into an issue with the ifupdown role.

My config was straightforward:

```
ifupdown__host_interfaces:
    'eno1':
        auto: 'True' 
        inet: 'static'
        inet6: 'auto'
        address: '10.0.0.2/29'
        gateway: '10.0.0.1'
        dns_nameservers:
        - '192.168.8.1'
        - '10.0.8.1'
```

This generates the following config on the target server:
```
allow-auto eno1 
allow-hotplug eno1
iface eno1 inet static
    address         10.0.0.2
    netmask         255.255.255.248
    gateway         10.0.0.1
    dns-nameservers 192.168.8.1 10.0.8.1
iface eno1 inet6 auto
```
Unfortunately, "allow-auto" and "auto" does not seem to behave in the same way and unless I have "auto eno1" in my config, the link is not up after networking is started. This is on fresh Debian 10 install.

I came across this thread that seems to suggest that there might be some ambiguity in the directives used:  https://lists.debian.org/debian-user/2017/09/msg00901.html 

Since the debops role already distinguishes between "auto" and "allow: auto" keys, perhaps "auto: 'True'" should simple generate  "auto <iface>" in the resulting config and not "allow-auto"?
