### ISSUE TITLE
debops.ferm

### ISSUE THREAD

**Issue by oguzhansrky** [debops/debops#1356]
Hi, 
First of all thank you to the developers.  A tremendous job has been done.

For example: I installed ispconfig on a machine with debops installed. # https://www.ispconfig.org/

Ssh is running on the machine. 

However, I was unable to open http, https, 8080, 19999 ports.

When the iptables-save command is run, the settings are deleted and I can connect.

How can I add and run these ports?

**Comment by drybjed** [comment]
@oguzhansrky Hi! ISPConfig and DebOps are equivalents ad I suspect that they will clash in a lot more ways than just the firewall configuration... In this case, `ferm` is configuring its own set of IP tables, and then ispconfig tries to apply their own set on top of that and the firewall is broken.

You can open these ports using the `ferm` role like this:
```yaml
ferm__rules:
  - name: 'open_custom_ports'
    dport: [ 'http", 'https', '8080', '19999' ]
    saddr: [ '192.0.2.0/24' ]
    protocol: 'tcp'
```
That should do the trick. Put it in the Ansible inventory, for example in `ansible/inventory/host_vars/<hostname>/ferm.yml` and apply the `ferm` role:
```
debops service/ferm -l hostname
```
