### ISSUE TITLE
[debops.pam_access] Wrong order of additional sshd rules for root

### ISSUE THREAD

**Issue by apapsch** [debops/debops#1364]
I want to allow root login for a certain address. In the host vars I have added (fake address):

```
pam_access__host_rules:
  - name: sshd
    state: append
    options:
      - name: allow-foo
        comment: 'Allow foo service'
        permission: allow
        users: root
        origins:
          - '255.255.255.255'
          - '.my.great.host'
```

The resulting rule will be placed in `/etc/security/access-sshd.conf` after the predefined user rules, specifically after:

```
# Deny access to root account via SSH from anywhere else
-:root:ALL
```

Thus, additional root rules have no effect. I'm unsure what the best mitigation would be.

* In the rule file template ensure root rules are printed first. Though surely `-:root:ALL` is just another rule? Additional rules would still be printed after the deny all rule.
* Remove the deny all rule from the list and print it implicitly. Though this would create unexpected side effects (along "I have 5 rules, why is it printing 6?") and it would remove freedom to misconfigure your server ;-)
* Support `state: prepend`

**Comment by drybjed** [comment]
Using the proposed solutions would be tricky because the `pam_access` role uses the `parse_kv_items` filter to process the configuration. But good news - there's a way to handle this already. Just add a `weight` parameter in your configuration:
```yaml
pam_access__host_rules:
  - name: sshd
    state: append
    options:
      - name: allow-foo
        comment: 'Allow foo service'
        permission: allow
        users: root
        origins:
          - '255.255.255.255'
          - '.my.great.host'
        weight: -60
```
With this, your rule will be inserted just before the `-:root:ALL` rule. You can tweak the weight parameter to move it higher or lower in the file.
