### ISSUE TITLE
[docker] docker_server__options has no effect

### ISSUE THREAD

**Issue by Ineluki** [debops/debops#1390]
The `docker_server__options` seems to have no effect.

config: 
```yaml
docker_server__upstream: True
docker_server__options:
  - '--insecure-registry=docker-reg.lan:5000'
```
Alternately tried it with an IP like in the example here https://docs.debops.org/en/master/ansible/roles/docker_server/defaults/main.html#envvar-docker_server__options but same results.

versions:
```
ansible-playbook 2.9.7
python version = 3.8.2
```

Expected result: put the insecure-registry option in either the /etc/docker/daemon.json or systemd exec parameters.

Actual result: insecure registry does not take effect. 
`Error response from daemon: Get https://docker-reg.lan:5000/v2/: http: server gave HTTP response to HTTPS client`

Changing the option has no effect: `changed=0`
