### ISSUE TITLE
tinc interfaces doesnt become bridge member

### ISSUE THREAD

**Issue by jankowa** [debops/debops#1398]
Tinc systemd service seems not to be waiting for the bridge to come ready if it's configured as a bridge port.

To reproduce on Debian Buster: Setting up a default tinc mesh described here with:

```
tinc__host_networks:
  'mesh0':
    bridge: 'br2'

ifupdown__interface_layout: 'static'
ifupdown__host_interfaces:
  'br2':
    type: 'bridge'
    inet: 'static'
    nat: True
    addresses:
      - '10.0.0.10/24'
```

works fine on setup (the only problem is that ifupdown role always looses connection and has to be done twice). But after reboot the tap-mesh0 interface isn't attched to br2.

`service tinc@mesh0 restart`

helps - and tinc is working again like expected.

```
:~# brctl show
bridge name	bridge id		STP enabled	interfaces
```

After
`  service tinc@mesh0 restart`

```
bridge name	bridge id		STP enabled	interfaces
br2		8000.deb203db0cd1	no		tap-mesh0
```
