### ISSUE TITLE
How to setup redis replication

### ISSUE THREAD

**Issue by retr0h** [debops/debops#1403]
I was reading the [docs](https://debops-documentation-testing.readthedocs.io/en/latest/ansible/roles/debops.redis.html?highlight=redis_hosts_master), but these seem outdated.

There is no longer a redis role but a redis_server role.  I don't see a way to pass extra values to redis.conf, altho I think this is probably due to my unfamiliarity with debops way of doing things.

For example redis.conf should have `slaveof` `slave-serve-stale-data`, etc... directives.  I am using debops redis roles standalone in another repository, and was hoping for pointers.

Thanks -
John

**Comment by tasosalvas** [comment]
Hey,

The current documentation lives in https://docs.debops.org/. I'm not really familiar with the redis roles but I hope that's some help.

I'm not sure what debops-documentation-testing.readthedocs.io is, I guess @drybjed will know.

**Comment by retr0h** [comment]
I think I am further along understanding.  It seems I must define the following if I wish to setup replication:

```
      redis_server__base_options:
        - name: slave-serve-stale-data
          value: "yes"
        - name: slave-read-only
          value: "yes"
        - name: repl-disable-tcp-nodelay
          value: "no"
        - name: repl-backlog-size
          value: 1mb
        - name: slave-priority
          value: 100
        - name: min-slaves-to-write
          value: 0
        - name: min-slaves-max-lag
          value: 10
```

etc...

**Comment by retr0h** [comment]
There does however appear to be a bug when providing `redis_server__base_options`.  We are skipping steps we should not skip for some reason.  Seems the when guard is skipping things when  specifying `redis_server__base_options`, on 2 different playbook runs.

So effectively one does not have the ability to apply a slightly diff configuration on the secondary redis servers:

```
        - name: slaveof
          value: "{{ hostvars[groups['redis_primary'][0]].ansible_eth0.ipv4.address }} {{ redis_port }}"
```

### Guard


```
when: item.name|d() and item.state|d('present') not in [ 'absent', 'init', 'ignore' ]
```

### Problematic play

```
- name: Setup Primary
  hosts: redis_primary
  gather_facts: true
  become: true
  roles:
    - role: debops.redis_server
      redis_server__bind: [ "{{ ansible_eth0.ipv4.address }}", 'localhost']
      redis_requirepass: false
      redis_server__auth_password: false
      redis_server__no_log: false
      redis_server__base_options:
        - name: slave-serve-stale-data
          value: "yes"
        - name: slave-read-only
          value: "yes"
        - name: repl-disable-tcp-nodelay
          value: "no"
        - name: repl-backlog-size
          value: 1mb
        - name: slave-priority
          value: 100
        - name: min-slaves-to-write
          value: 0
        - name: min-slaves-max-lag
          value: 10

- name: Setup Secondaries
  hosts: redis_secondary
  gather_facts: true
  become: true
  roles:
    - role: debops.redis_server
      redis_server__bind: [ "{{ ansible_eth0.ipv4.address }}", 'localhost']
      redis_requirepass: false
      redis_server__auth_password: false
      redis_server__no_log: false
      redis_server__base_options:
        - name: slaveof
          value: "{{ hostvars[groups['redis_primary'][0]].ansible_eth0.ipv4.address }} {{ redis_port }}"
        - name: slave-serve-stale-data
          value: "yes"
        - name: slave-read-only
          value: "yes"
        - name: repl-disable-tcp-nodelay
          value: "no"
        - name: repl-backlog-size
          value: 1mb
        - name: slave-priority
          value: 100
        - name: min-slaves-to-write
          value: 0
        - name: min-slaves-max-lag
          value: 10
```

However, if we combine the above into a single initial run, I do not receive this error.  Possibly, fact caching?

```
- name: Setup Primary
  hosts: all
  gather_facts: true
  become: true
  roles:
    - role: debops.redis_server
      redis_server__bind: [ "{{ ansible_eth0.ipv4.address }}", 'localhost']
      redis_requirepass: false
      redis_server__auth_password: false
      redis_server__no_log: false
      redis_server__base_options:
        - name: slave-serve-stale-data
          value: "yes"
        - name: slave-read-only
          value: "yes"
        - name: repl-disable-tcp-nodelay
          value: "no"
        - name: repl-backlog-size
          value: 1mb
        - name: slave-priority
          value: 100
        - name: min-slaves-to-write
          value: 0
        - name: min-slaves-max-lag
          value: 10
```

### Result

```
    TASK [debops.redis_server : Setup Redis local facts] ***************************
    changed: [instance-secondary-1]
    changed: [instance-secondary-2]

    TASK [debops.redis_server : Reload facts if they were modified] ****************
    ok: [instance-secondary-2]
    ok: [instance-secondary-1]

    TASK [debops.redis_server : Install custom Redis scripts] **********************
    changed: [instance-secondary-1]
    changed: [instance-secondary-2]

    TASK [debops.redis_server : Create Redis auth UNIX group] **********************
    changed: [instance-secondary-2]
    changed: [instance-secondary-1]

    TASK [debops.redis_server : Create Redis instance directories] *****************
    skipping: [instance-secondary-1]
    skipping: [instance-secondary-2]

    TASK [debops.redis_server : Install the original Redis config file to instance] ***
    skipping: [instance-secondary-1]
    skipping: [instance-secondary-2]

    TASK [debops.redis_server : Generate dynamic Redis configuration scripts] ******
    skipping: [instance-secondary-1]
    skipping: [instance-secondary-2]

    TASK [debops.redis_server : Generate static Redis configuration files] *********
    skipping: [instance-secondary-1]
    skipping: [instance-secondary-2]

    TASK [debops.redis_server : Remove include line from redis.conf] ***************
fatal: [instance-secondary-1]: FAILED! => {"msg": "'dict object' has no attribute 'results'"}
fatal: [instance-secondary-2]: FAILED! => {"msg": "'dict object' has no attribute 'results'"}
```

**Comment by drybjed** [comment]
Just a quick heads-up, it looks like that version of the documentation was set up long time ago by @ypid, I guess it's time to bring it down. :-)

**Comment by drybjed** [comment]
@retr0h Hello and thanks for trying out DebOps. Unfortunately it seems that you started with one of the most complex roles. :-)

Managing Redis with Ansible is complicated - Redis modifies its own configuration files at runtime and Ansible needs to take these changes into account to not break things every other run. On top of that is DebOps style of configuration where we assume that users don't modify the roles directly but configure them via Ansible inventory, and it all combines into a hard to understand configuration engine.

You should perhaps start by reading the [Redis Server configuration pipeline](https://docs.debops.org/en/master/ansible/roles/redis_server/config-pipeline.html) section of the role documentation. It explains what variables are important and how static and dynamic configuration options are handled.

DebOps roles come with a default, sane configuration which tries to adapt to a given environment. It seems that you started right away with a custom playbook and overrode a set of base variables that are used to hold the original configuration, thus swiping the whole stack of variables right off the table.

If you want to use your own playbooks that's fine, but start slow - add just the `redis_server` role, with no variables, run the playbook and see how it sets things up. You should be able to define `redis_server__bind` list to bind Redis on the network interfaces just fine.

If you want to modify the configuration afterwards, you should read the [`redis_server__configuration`](https://docs.debops.org/en/master/ansible/roles/redis_server/defaults-detailed.html#redis-server-configuration) variable documentation. This is the variable you want to use, not `redis_server__base_options`. It will let you modify per-instance configuration.

When you are comfortable managing one Redis Server instance with the DebOps role, you can then set up a cluster - look at [`redis_server__instances`](https://docs.debops.org/en/master/ansible/roles/redis_server/defaults-detailed.html#redis-server-instances) variable documentation, it has some examples that can help you set them up. By the way, DebOps roles are designed with keeping the configuration in the Ansible inventory files and not in the playbook itself - that way you can set up multiple Redis instances at the group level and then pick one initial instance as a master.

If you still have issues let me know.

**Comment by retr0h** [comment]
Thanks @drybjed, I've written quite a bit of ansible, and I have found the debops way of dong things very interesting, esp as it has auto documentation, and incorporates everything as a mono-repo.  Cheers to you guys for the beautiful work.  I always find it very interesting to learn new ways of doing things.

**Comment by ypid** [comment]
> Just a quick heads-up, it looks like that version of the documentation was set up long time ago by @ypid, I guess it's time to bring it down. :-)

Sorry for the confusion. I forgot about that. I have now taken it down. Seems it might take a few minutes for the website to disappear.

**Comment by alinalexandru** [comment]
It doesn't work now because of notify added after changes made in config files.
```
- name: Generate dynamic Redis configuration scripts
  template:
    src: 'etc/redis/instance/ansible-redis-dynamic.conf.j2'
    dest: '/etc/redis/{{ item.name }}/ansible-redis-dynamic.conf'
    owner: 'root'
    group: '{{ redis_server__group }}'
    mode: '0750'
  with_items: '{{ redis_server__combined_configuration | debops.debops.parse_kv_items }}'
  when: item.name|d() and item.state|d('present') not in [ 'absent', 'init', 'ignore' ]
  register: redis_server__register_config_dynamic
  notify: [ 'Refresh host facts' ]
  no_log: '{{ debops__no_log | d(True) }}'

- name: Generate static Redis configuration files
  template:
    src: 'etc/redis/instance/ansible-redis-static.conf.j2'
    dest: '/etc/redis/{{ item.name }}/ansible-redis-static.conf'
    owner: 'root'
    group: '{{ redis_server__group }}'
    mode: '0640'
  with_items: '{{ redis_server__combined_configuration | debops.debops.parse_kv_items }}'
  when: item.name|d() and item.state|d('present') not in [ 'absent', 'init', 'ignore' ]
  register: redis_server__register_config_static
  notify: [ 'Refresh host facts' ]
  no_log: '{{ debops__no_log | d(True) }}'
```

This make the instance name to appear in `ansible_local.redis_server.instances` and task `Set Redis Server slave status on first install` to be skipped.
The fix will be to change the `when` condition, but I can not see any new expression.

As this is a one time step, we decided to run the command manually. 
The example defined there https://docs.debops.org/en/master/ansible/roles/redis_server/defaults-detailed.html#examples was working before those changes where done.
