### ISSUE TITLE
Issues with first run of PKI on a new host

### ISSUE THREAD

**Issue by sysbot** [debops/debops#1448]
not sure if anyone else experiencing the same issue i have with PKI role but im trying to trace down the issue, it seemed like a race condition somewhere where this line get run[1], which suppose to create `pki/realms/by-host/<new host>` on the controller, but somehow it didnt get to do that yet then this line get run[2], which attempting to sign for the current host but unable to do so because the certs for it dont exist yet, log for all this.

Configuration for PKI looking something like this
```

- name: Manage Public Key Infrastructure
- hosts: [ 'all_hosts' ]
  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'
  become: True
  become_method: sudo
  strategy: linear
  tags:
    - pki

  vars:

    pki_inventory_groups: [ 'service_pki' ]
    pki_acme: false
    pki_enabled: true
    pki_realms:
      - name: 'local'
  pre_tasks:

    - import_role:
        name: 'pki'
        tasks_from: 'main_env'
      tags: [ 'role::pki', 'role::pki:secret', 'role::secret' ]

  roles:
    - role: secret
      tags: [ 'role::secret', 'role::pki', 'role::pki:secret' ]
      secret_directories:
        - '{{ pki_env_secret_directories }}'

    - role: cron
      tags: [ 'role::cron', 'skip::cron' ]

    - role: pki
      tags: [ 'role::pki', 'skip::pki' ]
```

[1] https://github.com/debops/debops/blob/master/ansible/roles/pki/tasks/main.yml#L320
[2] https://github.com/debops/debops/blob/master/ansible/roles/pki/tasks/main.yml#L376
[3] https://gist.github.com/sysbot/10f6486637cd20b0d3722d0397176dce
