### ISSUE TITLE
[pki] Running the role as dependent fails to initialize new realms

### ISSUE THREAD

**Issue by tasosalvas** [debops/debops#1486]
So, Debops 2.1.1, I'm doing this in my role's playbook:
```yaml
pre_tasks:
  - import_role:
      name: 'pki'
      tasks_from: 'main_env'
    tags: [ 'role::pki', 'role::pki:secret', 'role::secret' ]
    vars:
      pki_dependent_realms: '{{
        lookup("template", "lookup/webnames__pki_realms.yml.j2") | from_yaml
      }}'

roles:
  [...] more stuff happens

  - role: pki
    pki_dependent_realms: '{{
      lookup("template", "lookup/webnames__pki_realms.yml.j2") | from_yaml
    }}'
```

And get (sanitized a bit to exclude some of my info):
```
TASK [pki : Download private realm contents by host] ***
[...]
'domain' and realms initially installed by service/pki run happily.
[...]
If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [staging_host] (item={'name': 'clientdomain.gr', 'domain': 'clientdomain.gr', 'subdomains': ['www', 'dev'], 'acme': True, 'acme_subdomains': ['www', 'dev']}) => changed=false
  ansible_loop_var: item
  invocation:
    dest: /etc/pki/realms/clientdomain.gr/private/
    group: ssl-cert
    mode: '0640'
    module_args:
      dest: /etc/pki/realms/clientdomain.gr/private/
      group: ssl-cert
      mode: '0640'
      owner: root
      src: [ansibledir]/secret/pki/realms/by-host/staging_host/clientdomain.gr/private/
    owner: root
    src: [ansibledir]/secret/pki/realms/by-host/staging_host/clientdomain.gr/private/
  item:
    acme: true
    acme_subdomains:
    - www
    - dev
    domain: clientdomain.gr
    name: clientdomain.gr
    subdomains:
    - www
    - dev
  msg: |-
    Could not find or access '[ansibledir]/secret/pki/realms/by-host/staging_host/clientdomain.gr/private/' on the Ansible Controller.
    If you are using a module and expect the file to exist on the remote, see the remote_src option
```

Placing the item into `pki_realms` in inventory fails with the same error when running my playbook.
The paths to the local pki realm dirs are correct but do not get created.

Running `service/pki` with my realms placed in `pki_realms` works fine, and my role's `pki_dependent_realms` (duplicate, at this point, of what's in `pki_realms`) passes over it idempotently without errors on subsequent runs.

I didn't find an example of `pki_dependent_realms` being used anywhere outside the `pki` role in the codebase.
I had a peek at the code and the variable seems to be in place in the relevant parts (the temlate used by `main_env.yml` and the `Download private realm contents by host` task).
I might be missing something about using dependent roles, although I'm using a bunch of others without issue.

Anyhow, if it's a bug and you can help me spot I'd be happy to fix it.

Anyway, I would have mentioned this on IRC, as I may be making some mistake somewhere and this might not be issue-worthy, but my connection is dropping several times per minute these past few days and I don't want to spam you with all that.
