### ISSUE TITLE
ifupdown apply handler problem

### ISSUE THREAD

**Issue by gazoo4** [debops/debops#150]
Hello,

while testing out the tinc playbook which requires ifupdown underneath I came across the following issue which I can't seem to be able to get my head around and I suspect this is a bug in the handler script.

My testing environment is Ubuntu 16.04.3 (laravel/homestead) on the nodes built by Vagrant (see the attached Vagrantfile in case you want to reconstruct it).

The aim is to create mesh network out of 3 nodes:
```
all:
  children:
    debops_service_tinc:
      hosts:
        first:
        second:
        third:
    debops_service_ifupdown:
      hosts:
        first:
        second:
        third:
```

I'm applying the minimal set roles in my playbook in order to get the basic config up:
```
- role: debops.tinc/env
- role: debops.ifupdown/env
- role: debops.secret
  secret__directories: '{{ tinc__env_secret__directories }}'
- role: debops.tinc
- role: debops.ifupdown
```

My nodes are configured as follows (IP naturally differs):
```
ifupdown__host_interfaces:
  'tun0':
    type: 'tunnel'
    inet: 'static'
    addresses: [ '192.0.2.21/24' ]
```

And the variables I set are the following:
```
# Define 'elasticnet' VPN network
tinc__host_networks:
  'elasticnet': # VPN network name
    port: '655' # Default port number
    interface: 'tun0' # Align with the ifupdown__*_interfaces value
    link_type: 'static' # No interest in DHCP

# By default network 'mesh0' is created. We don't want that.
tinc__default_networks: {}

# Assume no default interfaces for ifupdown
ifupdown__default_interfaces_map: {}

# Testing on a private network
tinc__host_addresses: '{{ tinc__host_addresses_fqdn +
                          tinc__host_addresses_ip_public +
                          tinc__host_addresses_ip_private }}'
```

The error I'm getting is the following (I did some formatting for better readability):
```
RUNNING HANDLER [debops.ifupdown : Apply ifupdown configuration] ****
fatal: [first]: FAILED! => {"changed": true, "failed": true, "msg": "non-zero return code", "rc": 1, "stderr": "Shared connection to 192.168.1.11 closed.\r\n",
"stdout": "...",
"stdout_lines": ["Detected interfaces to reconfigure: eth0,eth1,tun0",
  "Found active systemd ifup@ instances: eth0",
  "The 'tun0' interface is inactive",
  "Bringing down 'eth1' interface",
  "The 'eth1' interface is still active, shutting down networking service",
  "Bringing down 'eth0' interface due to desynchronized networking",
  "Bringing down '' interface due to desynchronized networking",
  "Bringing down 'eth0' interface",
  "Error: Script was working on 'eth0' network interface when it lost knowledge about the network interface state. The '/etc/network/interfaces.d/' might be desynchronized. Exiting to avoid loss of connectivity, investigate the issue."]} 
```

I don't think it's a correct behavior of the script if it tries to apply changes on any other interface than 'tun0' which is defined in the config file.

I'm attaching my full configuration.
[tinc_basic_example.tar.gz](https://github.com/debops/debops/files/1706477/tinc_basic_example.tar.gz)

Steps to reproduce:
1) install vagrant
2) unpack the attachment
3) in the project folder execute
```
ansible-galaxy install -r requirements.yml
vagrant up
ansible-playbook -i inventory.yml site.yml
```

Thanks in advance.

**Comment by drybjed** [comment]
Hello, thanks for the bug report.

In the provided configuration, I can see that you se some of the `debops.ifupdown` variables that are no longer used, for example `ifupdown_interfaces` (note the single underscore, not double). You should check if the variables you are using are correct.

It looks like `debops.ifupdown` tries to reconfigure the Ethernet interface it found using `ifupdown__ethernet_interfaces` variable and lookup within. I would start by inspecting the value of `ifupdown__combined_interfaces`. Add a task in the `debops.ifupdown/env/tasks/main.yml`:
```yaml
- debug: var=ifupdown__combined_interfaces
- meta: end_play
```
With this you can see what configuration the role will try to apply on the host. You can then try and disable `ifupdown__ethernet_interfaces` in the inventory, see if that changes the configuration.

I don't remember at the moment if I tested the role working without `ifupdown__ethernet_interfaces` because they are used in some lookups, but hopefully it should work. Let me know what you find.

**Comment by gazoo4** [comment]
Thank you for your quick reply.

Even when disabling the `ifupdown__ethernet_interfaces` I still see `br(0|1)` and `eth(0|1)` coming up among the `ifupdown__combined_interfaces`. Would you have any other idea what else to check? I understand that `eth0|1` are existing interfaces on the node and could be looked-up, but what surprised me was to see the bridge interfaces appearing.

**Comment by drybjed** [comment]
The lookup uses the `ifupdown__default_interfaces` variable, perhaps if you mask this one the `eth` and `br `interfaces won't show up.

BTW, what happens if you don't configure the Tinc interface and use the default `debops.ifupdown` configuration - does the role reconfigure the interfaces to be bridges, or the same issues show up?

Since you are doing this in Vagrant, check if perhaps the `systemd-networkd` is used to configure the interfaces. This might interfere with `ifupdown` operating properly.

**Comment by gazoo4** [comment]
Thanks for leading me in the right direction. To sum up - in order to make the handler working we need to mask both:
```
# By default the system looks-up eth and br interfaces. We don't want that.
ifupdown__default_interfaces: {}

# By default the ethernet interfaces are re-configured. We don't want that
ifupdown__ethernet_interfaces: {}
```

Perhaps it would make sense to make it explicit in the [tinc documentation](https://docs.debops.org/en/latest/ansible/roles/debops.tinc/getting-started.html#example-inventory).

**Comment by drybjed** [comment]
Sounds good. However I designed `debops.tinc` to be used with `debops.ifupdown` that configures the bridges, etc., basically it's a normal environment for that role. It is you that tried to mess with the defaults by only configuring Tinc interface and leaving the rest. :-)

Want to add a section about disabling the `debops.ifupdown` config this way via a PR?

**Comment by gazoo4** [comment]
You tell me - if you see my use-case as being outside of the target scope for this playbook then I don't think we should update it. Otherwise I can of course.

**Comment by drybjed** [comment]
I don't use DebOps roles as standalone, however many other users do. Having tips for them in the documentation about using the roles in a different way is fine with me, that's why the documentation is there in the first place. You can create a PR for it, just mark this as a specific use case where you don't want to modify existing network configuration.

BTW, did it all work as expected? The `debops.ifupdown` role replaces the `/etc/network/interfaces` file, did you had any issues with that?

**Comment by gazoo4** [comment]
Will do so.

The handler problem has been fixed by the masking. However the VPN is not yet working. The nodes can't see each other even despite the fact that the configuration in `/etc/tinc/*` looks correct from the first glance.

**Comment by drybjed** [comment]
Maybe the `debops.ferm` role needs to have forwarding enabled? Try setting `ferm__forward` to `True` and reconfiguring `ferm`.

Firewall forwarding is currently very awkward to configure and it probably needs to be moved to a separate role that uses `debops.ferm` as a dependency. Then, roles that require forwarding can pull that new role as a dependency along with `debops.ferm` and there's no need to fumble with `ferm__forward` anymore.

**Comment by gazoo4** [comment]
Thank you for the hint. I did try that and it didn't have a positive effect. I don't think a packet forwarding should make a difference in this setup as I'm trying to establish a connection between 2 (or 3) nodes in the TINC VPN and whether they act as a router or not should make no difference as they are directly connected between each other.

But looking into the TINC logs when starting it in the manual and debug mode `tincd -d5 -D` I don't see the connection has been established.

**Comment by drybjed** [comment]
TCPwrappers shouldn't affect Tinc, but maybe `iptables` is not properly configured? I don't see `debops.ferm` in the list of roles you claim to use, and [it is used in the `debops.tinc` playbook](https://github.com/debops/debops/blob/master/ansible/playbooks/service/tinc-plain.yml#L28-L30).

**Comment by gazoo4** [comment]
Thanks for your reply.

Naturally I've addded the relevant roles and the variable switch:

```
  roles:
    # Prepare the environment
    - role: debops.tinc/env
      tags: [ 'role::tinc', 'role::tinc:secret', 'role::secret', 'role::ferm' ]

    - role: debops.ifupdown/env
      tags: [ 'role::ifupdown', 'role::ferm' ]

    # Create neccesary folders for sharing secrets
    - role: debops.secret
      tags: [ 'role::secret', 'role::tinc:secret' ]
      secret__directories: '{{ tinc__env_secret__directories }}'

    # Configure the VPN
    - role: debops.tinc
      tags: [ 'role::tinc' ]

    # Firewall
    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ tinc__env_ferm__dependent_rules }}'
        - '{{ ifupdown__env_ferm__dependent_rules }}'

    # Configure IPs on the newly created VPN interface and apply the change
    - role: debops.ifupdown
      tags: [ 'role::ifupdown' ]
```
and then:
`ferm__forward: True`

Thank you. Let me know if the complete project attached would help.
