### ISSUE TITLE
Post bootstrap issue with user mail forwarding option

### ISSUE THREAD

**Issue by julien-lecomte** [debops/debops#1516]
While running command:
`debops service/users --become-method su -K --limit rd-webhooks02.example.com -v`

Playbook chokes on "Configure user mail forwarding" which is set for all 3 users__accounts with

```
TASK [users : Configure user mail forwarding] ***********************************************************************************************************************************************
fatal: [rd-webhooks02.example.com]: FAILED! => 
  msg: Incorrect su password
```

```
users__accounts:
  - name: jdoe
    comment: "jdoe"
    create_home: True
    forward: 'jdoe@example.com'
    groups: [ 'adm' , 'admins', 'sshusers' ]
    password: '*'
    update_password: 'always'
```

On line 243 of debops/ansible/roles/users/tasks/main.yml 

I've had to change:
```
become_user: '{{ "root" if ((item.chroot|d())|bool) else item.name }}'
```

```
become_user: '{{ "root" if ((item.chroot|d(True))|bool) else item.name }}'
```

If this is the correct fix, I'm willing to create a MR.

**Comment by julien-lecomte** [comment]
Current playbook:
```
- import_playbook: debops/bootstrap.yml
- import_playbook: debops/service/core.yml
  
- name: Minimal configuration for all hosts
  hosts: [ 'debops_all_hosts', '!debops_no_common' ]
  gather_facts: True
  become: True

  pre_tasks:
    - import_role:
        name: 'sshd'
        tasks_from: 'main_env'
  roles:
    - role: system_groups
    - role: sudo
    - role: system_users
    - role: authorized_keys
    - role: users
                

```
