### ISSUE TITLE
Using debops.pki with debops.elasticsearch doesn't appear to be possible

### ISSUE THREAD

**Issue by jsenecal** [debops/debops#1520]
Using certificates generated by `debops.pki` is not working due to the fact that elasticsearch does not allow for files to reside outside elasticsearch's own folders.

Symlinking (manually) doesn't work either because a `java.nio.file.AccessDeniedException` is raised due to `debops.pki` setting the private folder acls as `group:elasticsearch:--x` and not `group:elasticsearch:r-x` when using:
```yaml
pki_private_dir_acl_groups: 
  - elasticsearch
pki_private_file_acl_groups: "{{pki_private_dir_acl_groups}}"
```

Is there a better solution to this madness ?
