### ISSUE TITLE
[nginx] Question about vhost raw options

### ISSUE THREAD

**Issue by krystophe** [debops/debops#1561]
Hi,

I want to setup a wordpress multi site, all locations work but I want to add this and I can't find a raw_input like debops apache role 

if (!-e $request_filename) {
        rewrite /wp-admin$ $scheme://$host$uri/ permanent;
        rewrite ^/[_0-9a-zA-Z-]+(/wp-.*) $1 last;
        rewrite ^/[_0-9a-zA-Z-]+(/.*\.php)$ $1 last;
}
 
How can I update my vhost with debops ?

**Comment by ypid** [comment]
The Apache role was a redesign with knowledge of the Nginx role and the Nginx role has not yet been updated. It is called `options` in the Nginx role. Example:

```yaml
  - name: 'something.example.com'
    type: 'proxy'
    options: 'proxy_buffering off;'
    location_list:
      - pattern: '= /robots.txt'
        options: |
          log_not_found off;
```

Refs:

* https://docs.debops.org/en/master/ansible/roles/nginx/defaults-detailed.html#common-webserver-options
* https://docs.debops.org/en/master/ansible/roles/apache/defaults-detailed.html
