### ISSUE TITLE
mariadb: grant privileges fails when mariadb__users.*.name is not set

### ISSUE THREAD

**Issue by alemonmk** [debops/debops#1581]
In Default variable details of document of debops.mariadb, it is allowed to use `user` **or** `name` in `mariadb__users` to define a user. The major difference between them is `name` will be used to determine the database name for granting default privileges if `database` is not defined.

From [tasks/manage_contents.yml](https://github.com/debops/debops/blob/v2.1.2/ansible/roles/mariadb/tasks/manage_contents.yml):
```
- name: Grant default privileges to users
  mysql_user:
    login_unix_socket: '/run/mysqld/mysqld.sock'
    name: '{{ item.0.user | d(item.0.name) }}'
    host: '{{ item.0.host | default(mariadb__client) }}'
    priv: '{{ (item.0.database | d(item.0.name)) + ".*:" + mariadb__default_privileges_grant }}'
    append_privs: True
  with_together:
    - '{{ mariadb__users + lookup("flattened", mariadb__dependent_users, wantlist=True) + mariadb_users|d([]) }}'
    - '{{ mariadb__register_create_users.results }}'
  delegate_to: '{{ mariadb__delegate_to }}'
  when: ((item.0.user|d(False) or item.0.name|d(False)) and
         (item.0.state is undefined or item.0.state != "absent") and
         mariadb__default_privileges|d(False) and
         (item.0.priv_default is undefined or item.0.priv_default))
  no_log: True
```
Looks like `user` and `name` can both be defined, the former overrides latter, however when `user` is used, `database` is no longer optional. Otherwise it will fail will a pretty obscure error:
```
The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'name'

The error appears to be in '/home/user/.ansible/collections/ansible_collections/debops/roles01/roles/mariadb/tasks/manage_contents.yml': line 103, column 3, but may be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
- name: Grant default privileges to users
  ^ here
```

IMO I would remove `user` from `mariadb__users` as it is semantically redundant in a "user" list.
