### ISSUE TITLE
Unable to define a PKI realm in dependent variable for non-debops-playbook

### ISSUE THREAD

**Issue by reixd** [debops/debops#1594]
Hello @drybjed,

currently I am running into a problem when executing a custom non-debops-playbook to execute custom roles. I am using DebOps to install a "base system" default settings, PKI and nginx. Nothing fancy.

Now, in the custom playbook I defined several PKI realms in order to get LE TLS certs. However I am getting an error when executing the custom playbook, after all servers have been bootstrapped+configured by DebOps correctly.

Basically `debops.pki` is unable to `sign-by-host` because it cannot find the realm locally. However the realm is created correctly in the server...

Here is the redacted error message:

```
TASK [pki : Sign certificate requests for current hosts] *********************************************************************************************************************************************************************************************************************************
task path: /home/alice/projects/mydebopsproject/.venv/debops/lib/python3.8/site-packages/debops/ansible/roles/pki/tasks/main.yml:373
fatal: [srv02.example.com]: FAILED! => changed=false 
  cmd:
  - ./lib/pki-authority
  - sign-by-host
  - srv02.example.com
  delta: '0:00:00.103459'
  end: '2021-01-06 01:14:40.031104'
  msg: non-zero return code
  rc: 1
  start: '2021-01-06 01:14:39.927645'
  stderr: |-
    pki-authority: Error: failed to run ca -batch -notext -in /home/alice/projects/mydebopsproject/ansible/secret/pki/requests/domain/srv02.example.com/grafana.sub.example.com/request.pem -out /home/alice/projects/mydebopsproject/ansible/secret/pki/realms/by-host/srv02.example.com/grafana.sub.example.com/internal/cert.pem.tmp -config config/openssl-sign.conf (Exitcode: 1)
```

I am using the following role defaults:

```
myrole__domain: 'sub.example.com'

myrole__grafana_domain_list:
  - 'myrealm.{{ myrole__domain }}'

myrole__grafana_pki_realm: 'grafana.{{ myrole__domain }}'

myrole__pki__dependent_realms:
  - name: '{{ myrole__grafana_pki_realm }}'
    acme: true
    acme_ca: 'le-staging-v2'
    domains: '{{ myrole__grafana_domain_list }}'
    acme_domains: '{{ myrole__grafana_domain_list }}'

myrole__grafana_nginx__dependent_upstreams:

  - name: 'grafana_docker_upstream'
    enabled: True
    server: '127.0.0.1:3000'

myrole__nginx__dependent_servers:
  - name: '{{ myrole__grafana_domain_list }}'
    enabled: True
    pki_realm: '{{ myrole__grafana_pki_realm }}'
    filename: 'grafana.{{ myrole__domain }}'
    favicon: False
    location:
      '/': |
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_buffering off;
        proxy_pass http://grafana_docker_upstream;
```

And the custom playbook looks like this:

```
- name: Grafana Stack
  collections: [ 'debops.debops', 'debops.roles01',
                 'debops.roles02', 'debops.roles03' ]
  hosts:
    - 'monitoring'
  gather_facts: true
  become: true
  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'
  tags: [ 'play::monitoring', 'monitoring' ]

  pre_tasks:

    - import_role:
        name: 'myrole'
        tasks_from: 'main_env'
      tags: [ 'role::myrole', 'role::secret', 'role::myrole:env' ]

  roles:

    - role: secret
      tags: [ 'role::secret', 'role::pki', 'role::myrole:env' ]

    - role: pki
      tags: [ 'role::pki', 'skip::pki' ]
      pki_dependent_realms:
        - '{{ myrole__pki__dependent_realms }}'

    - role: nginx
      tags: [ 'role::nginx', 'skip::nginx' ]
      nginx__dependent_upstreams:
        - '{{ myrole__grafana_nginx__dependent_upstreams }}'
      nginx__dependent_servers:
        - '{{ myrole__nginx__dependent_servers }}'

    - role: myrole
      tags: [ 'role::myrole', 'skip::myrole' ]
```

Then I execute the playbook as usual:
```
debops ansible/playbooks/install_my_role.yaml -l monitoring
```

Looking at the source code of the `debops.pki` role I cannot find the cause.

Interestingly if I set the same PKI realm as an inventory host variable `ansible/inventory/host_vars/srv02.example.com/pki.yaml` it works :man_shrugging: 

```
---

pki_host_realms:
  - name: 'grafana.sub.example.com'
    acme: true
    acme_domains:
      - 'grafana.sub.example.com'
      
```

* Any ideas?
* Did I miss something?
