### ISSUE TITLE
owncloud using postgres  / No database password supplied / Using localhost by default

### ISSUE THREAD

**Issue by flohoff** [debops/debops#1596]
Hi,
ansible 2.9.6, Controller Debian/10, Host Ubuntu 18.04. Trying to install Nextcloud. 

```
TASK [owncloud : Automatically finish setup via the occ tool] ********************************************************************************************************************************************
fatal: [do]: FAILED! => changed=true 
  cmd:
  - /usr/local/bin/occ
  - maintenance:install
  - --data-dir=/srv/www/nextcloud/data
  - --database=pgsql
  - --database-name=nextcloud
  - --database-host=localhost
  - --database-user=nextclouduser
  - --database-pass=
  - --admin-user=admin-flo
  - --admin-pass=_foobar
  delta: '0:00:00.352990'
  end: '2021-01-10 22:35:53.396262'
  msg: non-zero return code
  rc: 1
  start: '2021-01-10 22:35:53.043272'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[08006] [7] FATAL:  no pg_hba.conf entry for host "::1", user "nextclouduser", database "nextcloud", SSL on
    FATAL:  no pg_hba.conf entry for host "::1", user "nextclouduser", database "nextcloud", SSL off
     ->
  stdout_lines: <omitted>

```

This is pretty strange as from looking at the owncloud__database_map defaults the dbhost should be set to /var/run/postgresql as default - not localhost. It seems one default overrides the other. And there seems to be no way from the default postgresql owncloud__database_map to set a dbuser password - https://docs.debops.org/en/master/ansible/roles/owncloud/defaults/main.html#envvar-owncloud__database_map

```
owncloud__database_map:

  # MySQL/MariaDB database.
  mariadb:
    dbtype: 'mysql'
    dbname: '{{ owncloud__database_name|d(owncloud__app_user) }}'
    dbuser: '{{ owncloud__database_user|d(owncloud__app_user) }}'
    dbpass: '{{ owncloud__database_password }}'
    dbhost: '{{ owncloud__database_server|d("localhost") }}'
    dbtableprefix: ''

  # PostgreSQL database on localhost, connection through Unix socket, no default password.
  postgresql:
    dbtype: 'pgsql'
    dbname: '{{ owncloud__database_name|d(owncloud__app_user) }}'
    dbuser: '{{ owncloud__database_user|d(owncloud__app_user) }}'
    dbpass: ''
    dbhost: '{{ owncloud__database_server|d("/var/run/postgresql") }}'
    dbtableprefix: ''

  sqlite:
    dbtype: 'sqlite'
```

Flo
