### ISSUE TITLE
debops.postfix: example for a group-related secret

### ISSUE THREAD

**Issue by stefangweichinger** [debops/debops#170]
I try to set use a specific sasl-sender user/pw via a postfix-lookup-table as you suggested.

It would be great to add an example to:

https://docs.debops.org/en/latest/ansible/roles/debops.postfix/defaults-detailed.html#postfix-lookup-tables

which shows how to use a file lookup with such a table that reads in a commonly used secret (= file within ansible/secret containing that password).

**Comment by stefangweichinger** [comment]
Suggested example, for revision:

```
postfix__lookup_tables:

  - name: 'smtp_sasl_password_maps.in'
    raw: '{{ lookup("file", secret + "/credentials/postfix/my_relayhost.yml") }}'

  - name: 'sender_canonical_maps.in'
    raw: |
        root smtp@example.com

  - name: 'sender_canonical_maps.regexp'
    raw: |
        /^(.*@).*$/ smtp@example.com
```

**Comment by drybjed** [comment]
Sounds good, however I would also add more "native" examples to not suggest that only `raw` can be used for this. Also, explanation of contents of the `my_relayhost.yml` file would be nice.

**Comment by stefangweichinger** [comment]
1. 

Sure, so far I haven't needed (or figured out...) anything else than "raw".

2.

```
postfix__relayhost: '[10.128.23.45]:587'
postfix__lookup_tables:

  - name: 'smtp_sasl_password_maps.in'
    raw: '{{ lookup("file", secret + "/credentials/postfix/my_relayhost.yml") }}'

# my_relayhost.yml
[10.128.23.45]:587 smtp_user:Secret_password
```

You prefer stuff like that as PRs against the docs itself, I assume?
