### ISSUE TITLE
[backup2l] Add possibility to disable mail sending from crontab

### ISSUE THREAD

**Issue by mathieumd** [debops/debops#1806]
Packages for backup2l [installs](https://packages.ubuntu.com/focal/all/backup2l/filelist) a [`/etc/cron.daily/zz-backup2l`](https://github.com/gkiefer/backup2l/blob/master/zz-backup2l) which says *Redirect its output if you do not want automatic e-mails after each backup.*

This could be an option offered by Debops role.

**Comment by mathieumd** [comment]
For what it's worth, I added this `post_tasks` to my playbook:

```yaml
    - name: '[backup2l] Disable cron mail sending'
      lineinfile:
        path: '/etc/cron.daily/zz-backup2l'
        regexp: '^([!#].*backup2l -b)$'
        line: '\1 >/dev/null'
        backrefs: yes
      tags: [ 'role::backup2l', 'skip::backup2l' ]
```

But of course it lacks all the magic of Debops!
