### ISSUE TITLE
unattended_upgrades__origins not applied?

### ISSUE THREAD

**Issue by mathieumd** [debops/debops#1815]
In the corresponding `host_vars` file I added:
```yaml
unattended_upgrades__origins:
  - origin: 'o=packages.gitlab.com/gitlab/gitlab-ce,n=${distro_codename},l=gitlab-ce'
  - origin: 'o=packages.gitlab.com/runner/gitlab-runner,n=${distro_codename},l=gitlab-runner'
```

But it's not applied by debops role `role::unattended_upgrades`: the `/etc/apt/apt.conf.d/50unattended-upgrades` file section persists to only be this:
```php
Unattended-Upgrade::Origins-Pattern {
        "o=Ubuntu,n=${distro_codename},a=${distro_codename}-security";
        "o=Ubuntu,n=${distro_codename},a=${distro_codename}-updates";
};
```

Is there anything I'm misunderstanding?
