### ISSUE TITLE
ifupdown not idempotent when deploying configuration from scratch

### ISSUE THREAD

**Issue by benaryorg** [debops/debops#1846]
After deleting most of `/etc/network/` in an attempt to get rid of potentially stale configuration, I seem to be unable to get debops to configure interfaces on Debian bullseye:

```yaml
---

ifupdown__interface_layout: manual
ifupdown__host_interfaces:
  - iface: ens18
    inet: static
    inet6: static
    auto: true
    addresses: [ 192.0.2.1/24, ]
    gateway: 192.0.2.254/24
    dns_nameserver: '{{ […] }}'
    dns_search: '{{ […] }}'
```

`/etc/network/interfaces` seems to include `/etc/network/interfaces.d`, hardcoded:

https://github.com/debops/debops/blob/157bbec844277a3b3c6dc27cbaa5f836f1173d1c/ansible/roles/ifupdown/templates/etc/network/interfaces.j2#L16

At the same time however the entire task seems to hardcode `/etc/network/interfaces.config.d`:

https://github.com/debops/debops/blob/157bbec844277a3b3c6dc27cbaa5f836f1173d1c/ansible/roles/ifupdown/tasks/main.yml#L71

https://github.com/debops/debops/blob/157bbec844277a3b3c6dc27cbaa5f836f1173d1c/ansible/roles/ifupdown/tasks/main.yml#L83

I've also been trying to get it to start the interface using systemd, but all scripts I'm finding in regard to that seem to use `ifquery`, which due to the above configuration does not yield any interfaces either.

https://github.com/debops/debops/blob/157bbec844277a3b3c6dc27cbaa5f836f1173d1c/ansible/roles/ifupdown/files/script/ifupdown-reconfigure-interfaces#L186-L187

This is my current `/etc/network` as configured by debops:

```
/etc/network
├── if-down.d
├── if-post-down.d
├── if-pre-up.d
├── if-up.d
├── interfaces
├── interfaces.config.d
│   └── 020_iface_ens18
├── interfaces.d
└── interfaces.dpkg-divert
```

The *020_iface_ens18* is usable, however it just isn't being loaded by anything.

Am I in error in thinking that there must be configuration in *interfaces.d* for this to work?
How can I get interfaces up at boot time on a server with static interfaces, static ips, and Debian bullseye, without having to resort to manual configuration?

**Comment by benaryorg** [comment]
My current workaround is this:

```yaml
ifupdown__custom_files:
  - dest: '/etc/network/interfaces.d/include-config'
    owner: 'root'
    group: 'root'
    mode: '0644'
    content: |
      # Include actual files, see https://github.com/debops/debops/issues/1846
      source /etc/network/interfaces.config.d/*
```

*Edit*: and this:

```yaml
# no old config, see https://github.com/debops/debops/issues/1846
resources__files:
  - path: /etc/network/interfaces.d/020_iface_ens18
    state: absent
```
