### ISSUE TITLE
system_users: Conditionally disable/expire users?

### ISSUE THREAD

**Issue by mathieumd** [debops/debops#1873]
I wonder what is the recommended way to conditionally remove, disable or expire an user without `system_users` or `users` roles creates it if actually absent?

For example, I want to expire the `ubuntu` user only on Ubuntu distributions, and the `pi` users on Raspbian.
- Should I use conditional syntax in `system_users__accounts`, something like this (awful but seems to work):
```yaml
system_users__accounts:
  - "{{
    { 'name': 'ubuntu',
    'uid': 1000,
    'expires': 1626704442,
    'sshkeys_exclusive': True,
    'sshkeys': '# Removed' }
    if ('Ubuntu' in ansible_facts['distribution']) else ''
    }}"
  - "{{
    { 'name': 'pi',
    'uid': 1000,
    'expires': 1626704442,
    'sshkeys_exclusive': True,
    'sshkeys': '# Removed' }
    if ("Raspbian" in ansible_facts['lsb']['id']) else ''
    }}"
```
- Or should I add a `system_users__group_accounts` in `inventory/group_vars/Ubuntu.yml`?
  - But then (if I understood well), I cannot use this variable anymore for other groups, which could be troublesome.
