### ISSUE TITLE
debops pki cannot remove domain from acme_domains

### ISSUE THREAD

**Issue by prk0ghy** [debops/debops#1908]
when deploying the role pki to a server with the following variables defined
```
---
# Special PKI realm for host
pki_acme_contacts: 
  - 'mailto:letsencrypt@mail.tld'
    # Can also include different domains like 'mail.example.org'
    # in the same realm.
pki_realms:
  - name: '{{ ansible_fqdn }}'
    acme: True
    acme_default_subdomains: []
    acme_ca: 'le-live-v2' #for production
    # acme_ca: 'le-staging-v2'
    acme_domains: [ 'cloud.server.tld', 'nextcloud.server.tld', 'git.server.tld' ]
```
and removing one of the acme_domains debops cannot remove the acme_domain from the pki realm on the server. This will cause the acme request to change, if for example a service got migrated to another server.

A workaround is to delete the realm entirely on the remote server and provision the pki role again.

**Comment by imrejonk** [comment]
Yes, this has unfortunately been a known problem for some time. I use the workaround you suggested. Work is being done on improving the role but it's quite a complicated one given all the reverse dependencies from other roles.

**Comment by Alphix** [comment]
I should add that adding a domain to `acme_domains` also doesn't work.

The reason is that `/usr/local/lib/pki/pki-realm` doesn't seem to update `/etc/pki/realms/<realm>/acme/openssl.conf` (and `/etc/pki/realms/<realm>/acme/request.pem`) if it already exists.

A more lightweight workaround is to:
1. Edit `/etc/pki/realms/<realm>/acme/openssl.conf` to add/remove `DNS.*` entries in the `[ ext_req_san ]` section
2. Move `/etc/pki/realms/<realm>/acme/request.pem` and `/etc/pki/realms/<realm>/acme/cert.pem` out of the way
3. Run `/usr/local/lib/pki/pki-realm run --name=<realm>` to generate a new cert

**Comment by dcasella** [comment]
Hi, just passing by to share my workaround which deletes the realm when the domain list differs between the `pki_group_realms` variable and the filesystem configuration file.

In the `pre_tasks` section (which run before the roles):

```yaml
- name: Get realm configuration
  register: realm_config
  changed_when: false
  failed_when: false # ignore missing file
  loop: "{{ pki_group_realms }}"
  loop_control:
    loop_var: realm
  ansible.builtin.command:
    cmd: cat /etc/pki/realms/{{ realm.name }}/config/realm.conf

- name: Remove realm configuration file if domains differ
  loop: "{{ realm_config.results }}"
  loop_control:
    label: "{{ item.realm }}"
  vars:
    domains_str: "config['domains']='{{ item.realm.domains | join('/') }}'" # as formatted in the config file
  when: "domains_str not in item.stdout" # removal condition
  ansible.builtin.file:
    path: /etc/pki/realms/{{ item.realm.name }}
    state: absent
```
