### ISSUE TITLE
Can't install package which depends on APT repository to be added

### ISSUE THREAD

**Issue by kenorb** [debops/debops#1925]
It seems the order of execution isn't quiet right, as I'm trying to install Docker from APT repository, but it fails before key and external repository has been added.

Playbook:

```
---
- name: Manage Docker configuration
  collections:
    - debops.debops
  hosts: all
  become: True
  roles:
    - role: apt
      tags:
        - role::apt
        - skip::apt
```

`group_vars/all/vars.yml`:

```
apt__enabled: True
apt__keys:
  - url: https://download.docker.com/linux/ubuntu/gpg
apt__packages:
  - docker-ce
apt__repositories:
  - repo: deb https://download.docker.com/linux/ubuntu groovy stable
```

The error is:

```
TASK [Gathering Facts] 
ok: [myhost]
META: ran handlers

TASK [debops.debops.apt : Install required packages] 
FAILED - RETRYING: Install required packages (3 retries left).
FAILED - RETRYING: Install required packages (2 retries left).
FAILED - RETRYING: Install required packages (1 retries left).
fatal: [myhost]: FAILED! => {"attempts": 3, "changed": false, "msg": "No package matching 'docker-ce' is available"}
```

and the whole playbook stops. And there is no tag which I can skip installing before adding the repo.

----

I've tried the following workaround, to run role twice with different set of vars, but it didn't work either:

```
    - role: apt
      tags:
        - role::apt
        - skip::apt
      vars:
        apt__packages: []

    - role: apt
      tags:
        - role::apt
        - skip::apt
```

**Comment by MartinAhrer** [comment]
Experiencing the same issue? Anyone with an idea. Have also tried the debops.docker_server role with no success.

**Comment by drybjed** [comment]
The `apt` role is more focused on configuring the APT package manager itself. The `apt__packages` variable can be used to install packages, but it will be executed way before any APT repositories or keys are configured.

If you really don't want to use the `docker_server` role which was written with installing Docker in mind, then the way I would do this is to configure the Docker GPG key and repository in the `apt` role, and then add `docker-ce` package to the `apt_install` role, which is executed after the APT configuration is in place. This should even work with the `common` playbook included with DebOps, no need to write a custom playbook.

**Comment by MartinAhrer** [comment]
I really wanted to use docker_server. As I was not able to make it work and got a similar error like the one here I gave this role a try. I understand now that the apt role is probably not a good idea. Thanks.

Here is what I tried with docker_server

```
roles:
      - role: docker_server
        tags: [ 'role::docker', 'skip::docker' ]
        docker_server__admins: "{{inventory_hostname_short}}_ansible"
        docker_server__upstream: true
        docker_server__upstream_edition: 'ce'
        docker_server__base_packages: []
```

This gives me a package docker-ce is not available error.
