### ISSUE TITLE
No package matching 'python-future'/'python-virtualenv' is available

### ISSUE THREAD

**Issue by kenorb** [debops/debops#1926]
```
TASK [debops.debops.python : Install requested packages]
...
fatal: FAILED! => {"attempts": 3, "changed": false, "msg": "No package matching 'python-future' is available"}
```

When ran on Ubuntu 20.04.3.

How to disable 'python-future' from being installed?

Playbook:

```
---
- name: Manage Docker configuration
  collections:
    - debops.debops
    - debops.roles01
  hosts: all
  become: True
  roles:
    - role: python
      tags:
        - role::docker_server
        - role::python
        - skip::python
      python__dependent_packages3:
        - '{{ docker_server__python__dependent_packages3 }}'
      python__dependent_packages2:
        - '{{ docker_server__python__dependent_packages2 }}'
    - role: docker_server
      tags:
        - role::docker_server
        - skip::docker_server
```

I think it's part of `python__base_packages2`?

I've removed:

```
      python__dependent_packages2:
        - '{{ docker_server__python__dependent_packages2 }}'
```

but it didn't help.

Host:

```
$ python --version
Python 2.7.18
$ python3 --version
Python 3.8.10
```

### Trace

```
The full traceback is:
  File "/tmp/ansible_ansible.legacy.apt_payload_Gvz0ya/ansible_ansible.legacy.apt_payload.zip/ansible/modules/apt.py", line 478, in package_status
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 301, in __getitem__
    raise KeyError('The cache has no package named %r' % key)
fatal: [myhost]: FAILED! => {
    "attempts": 3,
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false,
            "autoclean": false,
            "autoremove": false,
            "cache_valid_time": 0,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "fail_on_autoremove": false,
            "force": false,
            "force_apt_get": false,
            "install_recommends": null,
            "name": [
                "python3",
                "python3-apt",
                "python",
                "python-apt",
                "python3-httplib2",
                "python3-pip",
                "python3-setuptools",
                "python3-pycurl",
                "python3-future",
                "python3-virtualenv",
                "python3-wheel",
                "virtualenv",
                "python-httplib2",
                "python-setuptools",
                "python-pycurl",
                "python-future",
                "python-virtualenv",
                "python-wheel"
            ],
            "only_upgrade": false,
            "package": [
                "python3",
                "python3-apt",
                "python",
                "python-apt",
                "python3-httplib2",
                "python3-pip",
                "python3-setuptools",
                "python3-pycurl",
                "python3-future",
                "python3-virtualenv",
                "python3-wheel",
                "virtualenv",
                "python-httplib2",
                "python-setuptools",
                "python-pycurl",
                "python-future",
                "python-virtualenv",
                "python-wheel"
            ],
            "policy_rc_d": null,
            "purge": false,
            "state": "present",
            "update_cache": null,
            "update_cache_retries": 5,
            "update_cache_retry_max_delay": 12,
            "upgrade": null
        }
    },
    "msg": "No package matching 'python-future' is available"
}
```
