### ISSUE TITLE
bootstrap-sssd and bootstrap-ldap don't seem to be idempotent

### ISSUE THREAD

**Issue by Alphix** [debops/debops#1964]
Both ``nslcd`` and ``sssd`` contain configuration file generation tasks which include directives like:

```
  - name: Generate nslcd configuration
  ...
  when: nslcd__ldap_base_dn|d()
```

and:

```
  - name: Generate sssd configuration
  ...
  when: sssd__ldap_base_dn|d()
```

The ``nslcd__ldap_base_dn`` variables and ``sssd__ldap_base_dn`` variables are both defined as:

`'{{ ansible_local.ldap.base_dn|d([]) }}'`

In the ``bootstrap-*`` case, ``ansible_local.ldap.base_dn`` is initially undefined, and later set by the ``debops.ldap`` role.

However, the ``sssd__ldap_base_dn`` and ``nslcd__ldap_base_dn`` variables aren't recalculated, so the configuration files ``/etc/sssd/sssd.conf`` and ``/etc/nslcd.conf`` files aren't generated (in the latter case, a default file is generated by the DPKG package, so the fact the file is present is misleading).

I tried copying the trick from ``debops.ldap``:

```
- name: Take note of the current LDAP configuration
  set_fact:

    # Track the changes in the configuration state
    # between role executions in the same play.
    ldap__fact_configured: '{{ ldap__configured }}'

    # Re-instantiate dependent variables to evaluate variables that use them.
    # Without this, dependent variables may contain outdated configuration.
    ldap__fact_dependent_tasks: '{{ ldap__dependent_tasks }}'
  tags: [ 'role::ldap:tasks', 'skip::ldap:tasks' ]
```

To update ``sssd__ldap_base_dn`` and ``nslcd__ldap_base_dn``, but that doesn't seem to actually recalculate them. A simple workaround is to run the ``bootstrap-*`` scripts twice for a host...where the second invocation will show:

```
PLAY RECAP ***********************************************************************************
example                    : ok=200  changed=2    unreachable=0    failed=0    skipped=138  rescued=0    ignored=0   
```

(Note the ``changed`` value)

Would be happy to do a PR, but I'm kind of stumped here (tried on ``2.10.7+merged+base+2.10.8+dfsg-1`` from Debian unstable).
