### ISSUE TITLE
[tools/dist-upgrade] Buster => Bullseye upgrade fails on "set" option.

### ISSUE THREAD

**Issue by boucman** [debops/debops#1982]
when upgrading from buster to bullseye (using the latest stable-2.3 branch), I get the following error

```
TASK [Remove all APT preferences for backported packages] **********************************************************************************************************************************************************
fatal: [build-qualite]: FAILED! => changed=true 
  cmd: 'set -o nounset -o pipefail -o errexit && grep -lrIZ ''Pin: release .*=buster-backports'' /etc/apt/preferences.d | xargs -0 rm -f --'
  delta: '0:00:00.002731'
  end: '2022-01-18 10:36:47.073369'
  msg: non-zero return code
  rc: 2
  start: '2022-01-18 10:36:47.070638'
  stderr: '/bin/sh: 1: set: Illegal option -o pipefail'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

```

I have boiled it down to the following line in tools/dist-upgrade.yml

```yml
  - name: Remove all APT preferences for backported packages
      shell: "set -o nounset -o pipefail -o errexit && grep -lrIZ 'Pin: release .*={{ dist_upgrade_current_release }}-backports' /etc/apt/preferences.d | xargs -0 rm -f --"  # noqa no-handler
      when: dist_upgrade_register_replace is defined and dist_upgrade_register_replace is changed
```
The problem comse from the _-o pipefail_ part. The pipefail option of set does not exist under debian buster.

My shell-foo is not good enough to figure out why this option is here and if it is safe to remove

Thx for the help
