### ISSUE TITLE
Struggling with the docker_server role

### ISSUE THREAD

**Issue by marcelpilot** [debops/debops#2044]
Hello,

I've been trying to get the docker_server role to run on my machines. I managed to have the role properly install docker on a fresh environment, but if there is docker already installed on my target machine, it seems to not upgrade the existing installation? Not quite sure what I am doing wrong or if I am missing something important here.

The playbook:

```
- hosts: docker_nodes
  become: true
  gather_facts: true
  collections: [ 'debops.debops', 'debops.roles01',
                 'debops.roles02', 'debops.roles03' ]

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  vars:
    # set system_architecture as amd64 if it's x86_64
    system_architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

  pre_tasks:
      - name: Create docker user
        user:
            name: "{{inventory_hostname_short}}_ansible"
      - name: Create /etc/docker directory #for some reason debops doesn't create this for me and it will cause an error
        file:
          path: /etc/docker
          state: directory
      - name: Remove docker-compose file if it already exists 
        file:
          path: /usr/local/bin/docker-compose
          state: absent

  roles:
      - role: keyring
        tags: [ 'role::keyring', 'skip::keyring' ]
        keyring__dependent_apt_keys:
          - id: '9DC8 5822 9FC7 DD38 854A E2D8 8D81 803C 0EBF CD88'
            url: 'https://download.docker.com/linux/debian/gpg'
            repo: 'deb [arch={{system_architecture}}] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable'
            state: present

      - role: docker_server
        tags: [ 'role::docker', 'skip::docker' ]
        docker_server__admins: "{{inventory_hostname_short}}_ansible"
        # In case this playbook is being executed in a footloose environment, following line has to be added to the daemon.json file: "storage-driver": ""
        docker_server__custom_daemon_options: "{{ lookup('file','docker/etc/docker/daemon.json')|from_json }}"
        docker_server__upstream: true
        docker_server__upstream_edition: 'ce'
        docker_server__dns_nameserver: []

  post_tasks:
      - name: Restart docker containers
        raw: docker start $(docker ps -aq)
```
