### ISSUE TITLE
postgres role - version 14 of pg introduced breaking change in password_encryption

### ISSUE THREAD

**Issue by ser** [debops/debops#2078]
before version 14:
```
password_encryption = on
```
in 14: Available values: `md5`, `scram-sha-256`

so the role must distinguish between versions and in new version probably use `scram-sha-256` as default with an option to move back to `md5`

```
password_encryption = scram-sha-256
```

the most annoying thing is that with `password_encryption = on` version 14 does not start giving an error.

**Comment by goetzk** [comment]
For anyone who encounters this, it can be worked around - in a sense - with a custom cluster entry which sets the password encryption
```
postgresql_server__clusters:                                                                                          
  - name: pdns_cluster                                                                                                
    port: 5432                                                                                                        
    password_encryption: md5   
```
