### ISSUE TITLE
How do you handle multiples variables? (ex. ferm__group_rules)

### ISSUE THREAD

**Issue by mathieumd** [debops/debops#2102]
I have a machine `test` in both groups `g1` and `g2`, which each have their own `group_vars/{g1,g2}.yml` defining different Ferm rules:
```yaml
ferm__group_rules:
  - name: 'group1 rule'
    #...
```
and:
```yaml
ferm__group_rules:
  - name: 'group2 rule'
    #...
```
However, if I run the playbook as-is, [obviously only one](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#understanding-variable-precedence) of them is actually used.

How can you handle these cases?

I tried to "append" lists in each `group_vars/g[12].yml`, but it fails because of *recursive loop detected in template string*:
```yaml
ferm__g1_rules:
  - name: 'group1 rule'
    #...
ferm__group_rules: '{{ ferm__group_rules|d([]) + ferm__g1_rules }}'
```
```yaml
ferm__g2_rules:
  - name: 'group2 rule'
    #...
ferm__group_rules: '{{ ferm__group_rules|d([]) + ferm__g2_rules }}'
```
Of course I could manually maintain a list of lists in `group_vars/all.yml`, like below, but it's a pain to maintain...
```yaml
ferm__group_rules: '{{ ferm__g1_rules|d([])
  + ferm__g2_rules|d([])
  + ferm__g3_rules|d([]) }}'
```
