### ISSUE TITLE
[php] doesn't support php8.0, php8.1 on sury

### ISSUE THREAD

**Issue by hungpr0** [debops/debops#2142]
Hello,

It seems `php` role doens't support php8.0, php8.1
I set these variables:
```
php__sury: True
php__version_preference: ['php8.1']
```
These taks in `php/tasks/main_env.yml` failed because:
- the package `php8.1` isn't available. `php{{ $version }}` package is only avaialble on official debian repo, not on `sury` I think. In Debian 11, it is `php7.4`

```
apt-cache madison php8.1
N: Unable to locate package php8.1

apt-cache madison php7.4
    php7.4 | 7.4.28-1+deb11u1 | http://debianrepo/bullseye bullseye/main amd64 Packages
    php7.4 | 7.4.28-1+deb11u1 | http://debianrepo/bullseye-security bullseye-security/main amd64 Packages

```
```
- name: Detect PHP version from available packages
  environment:
    LC_ALL: 'C'
  ansible.builtin.shell: set -o nounset -o pipefail -o errexit &&
         apt-cache madison {{ php__version_preference | join(' ') }} \
           | awk '{print $3}' \
           | sed -e 's/^.*://' -e 's/\+.*$//' -e 's/\d+\.\d+//' \
           | awk -F'.' '{print $1"."$2}' \
           | head -n 1
  args:
    executable: '/bin/bash'
  register: php__register_version
  check_mode: False
  changed_when: False
  tags: [ 'role::php:pools', 'role::php:config' ]

- name: Detect PHP long version from available packages
  environment:
    LC_ALL: 'C'
  ansible.builtin.shell: set -o nounset -o pipefail -o errexit &&
         apt-cache madison {{ 'php' + php__register_version.stdout }} \
           | awk '{print $3}' | sed -e 's/^.*://' -e 's/\+.*$//' -e 's/\-.*$//' \
           | head -n 1
  args:
    executable: '/bin/bash'
  register: php__register_long_version
  check_mode: False
  changed_when: False
  tags: [ 'role::php:pools', 'role::php:config' ]

```
result:
```
php__register_version: ""
php__register_long_version: "7.4"
```
Host in the test is Debian 11

Edit: correct variable `php__version_preference`
