### ISSUE TITLE
pxe/tasks/debian_netboot.yml is broken in 2.3.6

### ISSUE THREAD

**Issue by pigulla** [debops/debops#2203]
Apparently an unresolved merge conflict was accidentally commited.

See here: https://github.com/debops/debops/blob/v2.3.6/ansible/roles/ipxe/tasks/debian_netboot.yml#L84

```yml
- name: Download Debian firmware tarballs
  get_url:
    url: '{{ item.firmware_url | d(ipxe__debian_netboot_firmware_mirror + "/" + item.release + "/"
                                   + item.firmware_version + "/firmware.cpio.gz") }}'
    dest: '{{ ipxe__debian_netboot_src + "/" + item.release + "/non-free/"
              + item.firmware_version + "/firmware.cpio.gz" }}'
    checksum: '{{ item.firmware_checksum | d(omit) }}'
<<<<<<< HEAD
  loop: '{{ ipxe__debian_netboot_combined_release_map | parse_kv_items }}'
=======
    mode: '0644'
  loop: '{{ ipxe__debian_netboot_combined_release_map | debops.debops.parse_kv_items }}'
>>>>>>> 720ffba19 ([ci] Fix issues found by ansible-lint v6.0.0)
  when: ipxe__debian_netboot_firmware|bool and item.name|d() and item.state|d('present') not in [ 'absent', 'ignore' ] and
        item.release in ipxe__debian_netboot_releases and item.firmware_version|d()
  register: ipxe__register_get_firmware
  until: ipxe__register_get_firmware is succeeded
```
