### ISSUE TITLE
[lxc] Means for defining bootgroups missing 

### ISSUE THREAD

**Issue by htgoebel** [debops/debops#2240]
debops is missing means for defining lxc bootgroups. bootgroups tell lxc which container groups to start and the start order. This is relevant if some containers depend on others.

From /etc/default/lxc:
```
# BOOTGROUPS - What groups should start on bootup?
#       Comma separated list of groups.
#       Leading comma, trailing comma or embedded double
#       comma indicates when the NULL group should be run.
# Example (default): boot the onboot group first then the NULL group
BOOTGROUPS=",production,staging"
```

**Comment by htgoebel** [comment]
Possible solution:
```
    - name: Set LXC bootgroups
      lineinfile:
        path: /etc/default/lxc
        regexp: '^BOOTGROUPS='
        line: >-
          BOOTGROUPS={{ lxc__bootgroups }}
```

with `lxc__bootgroups` defautling to `","` comma (AFAIU)
