### ISSUE TITLE
[cron] [question] how to use cron__dependent_jobs

### ISSUE THREAD

**Issue by hungpr0** [debops/debops#2286]
Hello,

Not sure if anyone is using `cron__dependent_jobs` variable of `cron` module. Please help to check. I have just created new role `myrole` and add the variable to its `defaults/main.yml`

on my `common.yml` playbook:

```
# common.yml
    - role: cron
      tags: ['role::cron', 'skip::cron']
      cron__dependent_jobs: '{{ myrole__cron__dependent_jobs }}'
    - role: myrole
      tags: ['role::myrole', 'skip::myrole']
```
on `myrole/defaults/main.yml`
```
# myrole__cron__dependent_jobs
myrole__cron__dependent_jobs:
  'myrole_backup_test':
    state: 'present'
    job: 'echo a > /dev/null'
    hour: '18'
    minute: '30'
    environment:
      MAILTO: 'admin@example.com'
```

When running playbook, I receive this error message
```
TASK [debops.debops.cron : Manage cron environment variables]
msg: '{{ lookup("template", "lookup/cron__combined_jobs.j2", convert_data=False) | from_yaml }}: {{ myrole__cron__dependent_jobs }}: ''myrole__cron__dependent_jobs'' is undefined'
```

If I move `myrole__cron__dependent_jobs` on `myrole/defaults/main.yml` to inventory file, it is working. Is there way to use `__cron__dependent_jobs` on `defaults/main.yml` of other roles?

Thank you!

**Comment by drybjed** [comment]
From what you are saying, it seems that you defined everything correctly but Ansible doesn't see the `myrole__cron__dependent_jobs` variable for some reason. Both roles are included in the playbook... Try this, add in the playbook:
```yaml
pre_tasks:

  - debug: var=myrole__cron__dependent_jobs
  - debug: var=cron__combined_jobs
```
Show the output of these tasks when you run the playbook.

**Comment by hungpr0** [comment]
Thanks for the hint.
I have resolved the issue. It is because I didn't put `myrole` role in common.yml playbook. I use `import_playbook`.

```
# site.yml
...
- import_playbook: common.yml
- import_playbook: myrole.yml
...
```
```
# common.yml
...
    - role: cron
      tags: ['role::cron', 'skip::cron']

    - import_playbook: 'myrole.yml'
...
```
```
# myrole.yml
...
    - role: cron
      tags: ['role::cron', 'skip::cron']
      cron__dependent_jobs: '{{ myrole__cron__dependent_jobs }}'

    - role: myrole
      tags: ['role::myrole', 'skip::myrole']
...
```

```
# myrole/defaults/main.yml
myrole__cron__dependent_jobs:
  'myrole_backup_test':
    state: 'present'
    job: 'echo a > /dev/null'
    hour: '18'
    minute: '30'
    environment:
      MAILTO: 'admin@example.com'
```
