### ISSUE TITLE
[question] parse_kv_items

### ISSUE THREAD

**Issue by hungpr0** [debops/debops#2287]
Hello,

I try to use `empty` of `debops.debops.parse_kv_items` but it seems the result isn't expected.
```
- name: Manage var
  collections: ['debops.debops', 'debops.roles01',
                'debops.roles02', 'debops.roles03']
  hosts: ['my_test_host']
  vars:
    test_var:
      - name: foo
        other_param: bar
      - name: fizz
        param2: buz
    test_var_after:
      "{{ test_var | debops.debops.parse_kv_items(empty={'some_param': 'other_param', 'empty_param': ['param1', 'param2']}) }}"
  tasks:
    - name: test
      ansible.builtin.debug:
        var: test_var_after
```

once I run the playbook, here is the output:
```
TASK [test] *************************************************************************************************************
Tuesday 28 February 2023  02:27:55 +0000 (0:00:06.844)       0:00:07.572 ******
ok: [my_test_host] =>
  test_var_after:
  - id: 0
    name: foo
    other_param: bar
    real_weight: 0
    separator: false
    state: present
    weight: 0
  - empty_param: buz
    id: 10
    name: fizz
    param2: buz
    real_weight: 10
    separator: false
    state: present
    weight: 0
```

I thought it should have this result:
```
ok: [my_test_host] =>
  test_var_after:
  - id: 0
    name: foo
    other_param: bar
    real_weight: 0
    separator: false
    state: present
    weight: 0
    some_param: bar
  - empty_param: buz
    id: 10
    name: fizz
    param2: buz
    real_weight: 10
    separator: false
    state: present
    weight: 0
    empty_param: buzz
```

I can't see `some_param` or `empty_param` in the output. It is different with the example in https://docs.debops.org/en/latest/ansible/roles/ansible_plugins/getting-started.html

Can you please try explain how to use it?
