### ISSUE TITLE
[machine] MOTD script unexpectedly removed

### ISSUE THREAD

**Issue by thiras** [debops/debops#2314]
The MOTDs get removed by the role itself just after being added.

Here is my `machine.yml`;

```yml
machine__motd_scripts:
  - name: "motd"
    content: |
      #!/usr/bin/env tclsh
      ...
```

Here is the output;

```
TASK [debops.debops.machine : Install dynamic MOTD scripts] *********************************************
changed: [example] => (item=motd)
ok: [example] => (item=ansible)
ok: [ansible] => (item=tail)

TASK [debops.debops.machine : Remove unknown MOTD scripts] **********************************************
changed: [example] => (item=motd)
```
