### ISSUE TITLE
[debops.dovecot] add submission protocol to dovecot__features

### ISSUE THREAD

**Issue by clahil-linum** [debops/debops#2326]
Just add the submission protocol to debops/debops/roles/dovecot/defaults/main.yml like this to enable the submission protocol. This allows dovecot to accept mail from any client with a custom dovecot (e.g. lua based) authentication.

```
--- main.yml.org 2023-04-12 09:53:35.184419840 +0200
+++ main.yml     2023-04-12 09:53:54.572293906 +0200
@@ -426,7 +426,7 @@
         comment: 'Currently active protocols'
         value: "{{ dovecot__features |
                    intersect(['imap', 'imaps', 'pop3',
-                              'pop3s', 'sieve', 'lmtp']) |
+                              'pop3s', 'sieve', 'lmtp', 'submission']) |
                    map('regex_replace', '^(imap|pop3)s$', '\\1') |
                    list | unique | join(' ') }}"
```
The remaining configuration could be done via 

```
dovecot__host_configuration:
  - section: 'submission virtual config'
    title: 'submission'
    options:
      - name: "submission_relay_host"
        value: "localhost"
```
