### ISSUE TITLE
dist-upgrade: remove workaround for user error?

### ISSUE THREAD

**Issue by prahal** [debops/debops#2353]
https://github.com/debops/debops/commit/445d8e1631a373892d265b8f81432bdbef298d49 "fix(playbooks): Fix buster to bullseye upgrade path "
```
    - name: Fix APT sources (buster/updates becomes bullseye-security)
      replace:
        dest: "{{ item.path }}"
        regexp: '\s{{ dist_upgrade_new_release }}/updates\s'
        replace: ' {{ dist_upgrade_new_release }}-security '
      with_items:
        - "{{ dist_upgrade_register_apt_sources.files }}"
      when: dist_upgrade_new_release == 'bullseye'
```
is only of use if the upgrade was done incorrectly beforehand (that is a "bullseye/updates" string was inserted in the sources.list.
This is shipped since  v3.0.0

Creating the correct string "bullseye-security" is done since v2.3.0 in commit https://github.com/debops/debops/commit/1798bdd3d246c4e036ce8fc78343806c68fb9f27 " [apt] Update security suite name " though it only changes /etc/apt/sources.list.

I believe it is not debops job to fix user errors (ie the "bullseye/updates" is not from debops .

So this commit should be reverted.

There was a missing piece in generating the proper bullseye security deb repo line but it was fixed in commit https://github.com/debops/debops/commit/03ba473a39bad10c1593b08447f9efd60c045800 "[apt] set new debian-security generic mirror url for newer Debian" Ie https://github.com/debops/debops/pull/2266 included in master in march the 17th of 2023. Not in a release yet.

**Comment by prahal** [comment]
I found out that this wrong "bullseye/updates" string can be generated by debops per:
```
    - name: Change current release in APT sources
      ansible.builtin.replace:
        dest: "{{ item.path }}"
        regexp: '{{ dist_upgrade_current_release }}'
        replace: '{{ dist_upgrade_new_release }}'
      register: dist_upgrade_register_replace
      with_items:
        - "{{ dist_upgrade_register_apt_sources.files }}"
      when: dist_upgrade_current_release in dist_upgrade_version_map.keys() and
            dist_upgrade_new_release is defined and dist_upgrade_new_release
```
also changes the release in all files under /etc/apt/sources.list.d , so it would replace "buster/updates" with "bullseye/updates" under /etc/apt/sources.d. So the above fixup is needed.

Closing.
