### ISSUE TITLE
workaround to apt_key DEPRECATION warning - Bookworm

### ISSUE THREAD

**Issue by gardouille** [debops/debops#2377]
A third-party repository on Debian Bookworm can lead to a warning on an `apt update`:
```
W: http://example.com/debian/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

These variables previously worked correctly with ≤Bullseye:
``` yaml
apt__keys:
  - url: 'https://example.com/debian/example.com.asc'
    state: 'present'

apt__repositories:
  - filename: 'my-repo'
    repo: 'deb https://example.com/debian/ stable main'
    state: 'present'
```

Pending [deb822_repository](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/deb822_repository_module.html) support in DebOps, as a first workaround (and not the cleanest), adding **keyring** parameter in `apt__*keys`:
  - Keyring file and repository filename should be the same.
  - Set **.gpg** extension to have a dearmored key.
``` yaml
apt__keys:
  - url: 'https://example.com/debian/example.com.asc'
    keyring: '/etc/apt/trusted.gpg.d/my-repo.gpg'
    state: 'present'

apt__repositories:
  - filename: 'my-repo'
```

apt-key(8) recommended to use **Signed-by** option (compatible DebOps 👍) with a keyrings directory such as /etc/apt/keyrings (not directly compatible with debops.apt 👎, at least i haven't find an easy solution).

See also [ansible issue #78063](https://github.com/ansible/ansible/issues/78063) for extra infos ;)
