### ISSUE TITLE
[bind] missing `state` fails zone/view configuration creation

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [debops/debops#2432]
In the current `master` branch of the documentation and the `master` branch of the code, BIND role documentation examples suggest to have views and zones without `state` attribute.  However, this behavior is not acceptable because of the following code piece:

https://github.com/debops/debops/blob/a4aa669b0a2e3febc719c237a01a866c879adac7/ansible/roles/bind/tasks/main.yml#L85-L102

I don't see anything wrong with the code, but missing documentation can be improved in the future.  This issue is created both for future references regarding "Make sure either zones or views are defined" error and possible documentation improvements in `debops.bind` role.

**Comment by Alphix** [comment]
No state is usually interpreted as "present" in DebOps roles, and the above logic doesn't really reflect that. But as far as I can remember, `debops.debops.parse_kv_items` should set an undefined `state` to `present`. @BerkhanBerkdemir: what did your inventory look like when you triggered this behaviour?

Anyway, I guess the logic above could be improved. A first thought would be to replace `selectattr("state", "eq", "present")` by `rejectattr("state", "in", "[init, absent, ignore]")`...buuut that doesn't work because `rejectattr` blows up when `state` is undefined.

I think a better option might be to replace this:
```
ansible.builtin.set_fact: 
  bind__tmp_top_views: '{{ bind__combined_zones 
                           | debops.debops.parse_kv_items(name="view") 
                           | selectattr("state", "eq", "present") }}'
...
ansible.builtin.set_fact: 
  bind__tmp_top_zones: '{{ bind__combined_zones 
                           | debops.debops.parse_kv_items(name="name") 
                           | selectattr("state", "eq", "present") }}'
```

With something like this:
```
ansible.builtin.set_fact: 
  bind__tmp_top_views: '{{ bind__tmp_top_views | d([]) + [ item ] }}'
loop: '{{ bind__combined_zones 
          | debops.debops.parse_kv_items(name="view") }}'
loop_control:
  label: '{{ item.view }}'
when: item.state | d("present") == "present"
...
ansible.builtin.set_fact: 
  bind__tmp_top_zones: '{{ bind__tmp_top_zones | d([]) + [ item ] }}'
loop: '{{ bind__combined_zones 
          | debops.debops.parse_kv_items(name="name") }}'
loop_control:
  label: '{{ item.name }}'
when: item.state | d("present") == "present"
```
