### ISSUE TITLE
Swap file deletion

### ISSUE THREAD

**Issue by vogll** [debops/debops#2462]
Hi,

I was trying to delete file(s) within `debops.swapfile` role . I have used suggested format of the variable, here is my playbook :

```
    - name: Remove swap files
      include_role:
        name: swapfile
      vars:
        ansible_system_capabilities_enforced: False
        swapfile__files:
          - path: /swap01
            state: absent

```
But I can't do this because that this task in the role was always true,  turn on the swap and prevent it from being deleted. Here is the snip : 

```
- name: Enable swap files
  command: 'swapon -p {{ item.item.priority | d(swapfile__priority) }} {{ item.item.path | d(item.item) }}'  # noqa no-handler
  with_items: '{{ swapfile__register_allocation.results|d([]) }}'
  when: (item is changed and item.state|d("present") != 'absent' and
         ((ansible_system_capabilities_enforced|d())|bool and
          "cap_sys_admin" in ansible_system_capabilities) or
         not (ansible_system_capabilities_enforced|d(True))|bool)
```        

I guess the problem is in the condition. The right prefix item.item.state is missing. My proposal :

```
- name: Enable swap files
  command: 'swapon -p {{ item.item.priority | d(swapfile__priority) }} {{ item.item.path | d(item.item) }}'  # noqa no-handler
  with_items: '{{ swapfile__register_allocation.results|d([]) }}'
  when: (item is changed and item.item.state|d("present") != 'absent' and
         ((ansible_system_capabilities_enforced|d())|bool and
          "cap_sys_admin" in ansible_system_capabilities) or
         not (ansible_system_capabilities_enforced|d(True))|bool)

```
