### ISSUE TITLE
PKI: ACME request not signed by Let's Encrypt but by our internal CA?

### ISSUE THREAD

**Issue by mathieumd** [debops/debops#2487]
Until now, I was only using the (great) [internal CA](https://docs.debops.org/en/master/ansible/roles/pki/internal-ca.html) of debops.pki. But today, on one machine, I need both the internal CA's cert (say `example.com`, from default realm `domain`), and a [Let's Encrypt](https://docs.debops.org/en/master/ansible/roles/pki/acme-integration.html) one (`example.net`, from this host realm). So in the inventory of this host, I added:
```yaml
pki_host_realms:
  - name: 'example.net'
    acme: True
    acme_subdomains: [ 'www' ]
    acme_ca: 'le-staging-v2'
```

But when I run the PKI role on this host, this realm `example.net`'s cert is created, but it's signed by our internal CA, not by Let's Encrypt! (and it's *Subject Alternative Name* includes the default `domain` realm wildcard, although the `acme_subdomains` does not include it)

```sh
openssl x509 -noout -text -in example.net/default.crt
...
        Issuer: O = My Organisation, OU = Domain CA, CN = My Organisation Domain CA
        Subject: CN = example.net
...
            X509v3 Subject Alternative Name:
                DNS:example.net, DNS:*.example.net
```

Moreover, if I run again the role, then the task `Sign certificate requests for current hosts` now always fails:
```
TASK [debops.debops.pki : Sign certificate requests for current hosts] ********************************
fatal: [myhost -> localhost]: FAILED! => [...], "stderr": "pki-authority: Error: 
failed to run verify -CAfile issuer/subject/cert.pem -untrusted subject/cert.pem 
/home/mathieu/ansible/secret/pki/realms/by-host/myhost/example.net/internal/cert.pem 
(Exitcode: 2)\n\nDetails:\nCN = example.net
\nerror 47 at 0 depth lookup: permitted subtree violation
\nerror /home/mathieu/ansible/secret/pki/realms/by-host/myhost/example.net/internal/cert.pem:
 verification failed", [...]
```

Which is actually expected, because this CA signs domains under `example.com`, not `example.net`. But why this task successed at the first run of the role?!
```
TASK [debops.debops.pki : Sign certificate requests for current hosts] ********************************
ok: [myhost -> localhost]                                                                                                                                                                                                                                                                                                                                                                     
```

What am I missing?

**Comment by mathieumd** [comment]
(In case it could be important, I should explicitly say that `example.net` is actually `foo.example.net`)

**Comment by mathieumd** [comment]
Even if I set only `pki_default_realms` for this host (which overwrite the default `domain` realm), it's certificate still get signed by our Debops CA! I really don't understand why. 🤔

```yaml
pki_default_realms:
  - name: 'foo.example.net'
    acme: True
    # This `www` is actually *not* added to SAN!
    #             X509v3 Subject Alternative Name:
    #                 DNS:foo.example.net
    acme_subdomains: [ 'www' ]
    acme_ca: 'le-staging-v2'
    # Have to unset default_subdomains, otherwise `*.foo.example.net` is added to SAN.
    #             X509v3 Subject Alternative Name:
    #                 DNS:foo.example.net, DNS:*.foo.example.net
    default_subdomains: []
```
```sh
openssl x509 -noout -text -in /etc/pki/realms/foo.example.net/default.crt
#...
        Issuer: O = My Organisation, OU = Domain CA, CN = My Organisation Domain CA
```

**Comment by garethhowell** [comment]
I'll prefix this by emphasizing that I am not an expert. I found this whilst trying to debug my own pki.

For ACME to work, there needs to be a debops-managed, internet-accessible server running nginx so that the acme-challenge will work. See [https://docs.debops.org/en/master/ansible/roles/nginx/acme-support.html#how-acme-support-works](https://docs.debops.org/en/master/ansible/roles/nginx/acme-support.html#how-acme-support-works)

**Comment by mathieumd** [comment]
Thanks @garethhowell for trying :)

The machines where I tried are Debops-managed, and are directly reachable from Internet (ie. no corporate firewall or anything) with the domain that should be requesting Let's Encrypt certs.

I tried today on a second machine, and it's the same behaviour: the realm is created, it's `default.crt` is created for the required domain, **but** it's signed by our *internal* CA instead of Let's Encrpt! :-/

**Comment by garethhowell** [comment]
Have you directed the public-facing Nginx server to use the acme certificate?

In my case I needed to add:
```
nginx_pki_realm: 'example.net'
```
in the relevant `inventory/host_vars` file.

**Comment by mathieumd** [comment]
It could well be that, because the machine default domain is different from the one I wanted for ACME. Thank you!

Unfortunately, the machines where I needed it gone to production (with manually bootstrapped `certbot`), so I can't play with them anymore to confirm. But I will be sure to try it out the next time we'll need it; and of course I will post it here. Could be months until then, though.

**Comment by mathieumd** [comment]
Finally, I got to work on it again, and made it work. In addition to `nginx_pki_realm` (thanks @garethhowell), I had to add `pki_acme` and `pki_create_acme_challenge_dir` too. Here is a working `host_vars`:

```yaml
pki_realms:
  - name: 'nextcloud.example.com'
    acme: True
    acme_default_subdomains: []
    # acme_domains: [ 'cloud.example.com' ]
    # Until ACME tests are validated, stay on Staging
    acme_ca: 'le-staging-v2'

# Force ACME when your host does not have a public IP
#   https://docs.debops.org/en/master/ansible/roles/pki/acme-tiny-integration.html#prerequisites
pki_acme: True
pki_create_acme_challenge_dir: True

# As Let's encrypt ended it's expiration notification the contact settings does
# not work anymore. See:
#   https://github.com/debops/debops/issues/2603
pki_acme_contacts: []

nginx_pki_realm: 'nextcloud.example.com'
nginx__dependent_servers:
  - name: 'nextcloud.example.com'
    acme: True
    #...
```

It was a bit painful to find out which vars was needed. I wonder if it could have been easier?
