### ISSUE TITLE
APT: the apt__repositories item signed_by doesn't work

### ISSUE THREAD

**Issue by btcoolboy** [debops/debops#2491]
The apt__repositories item signed_by doesn't work. If I use apt__keys, will get below message when I use apt.
"Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details."

**Comment by seven-beep** [comment]
Hello, 

Here an example of functional configuration:

```` yaml
apt__repositories:

  - name: 'mise'
    filename: 'mise.sources'
    uris: 'https://mise.jdx.dev/deb'
    types: 'deb'
    suites: 'stable'
    components:
      - 'main'
    signed_by: 'https://mise.jdx.dev/gpg-key.pub'
````

@btcoolboy: I know it passed quite a few time but you did not provided what configurations did not work for you so the issue is unclear. Do you mind close this issue or provide more information ?
