### ISSUE TITLE
[debops.debops_legacy] New role which helps with DebOps upgrades/removes legacy files

### ISSUE THREAD

**Issue by ypid** [debops/debops#252]
Often, redesigns of existing roles result in new filenames on managed hosts. Old files currently don’t get removed by DebOps and just lay on managed hosts. This can become an issue because the old files are still in effect. Currently, the admin is expected to review all changes to DebOps and remove those files manually. I propose we create a role which deletes common legacy files to centralize this effort.

The role does not need to do much. I would keep the scope minimal for now. Just delete legacy files. I maintain a list for this already using the `debops.resources` role. Example:

```YAML
resources__files:

  - path: '/etc/sysctl.d/80-local.conf'
    state: 'absent'

  - path: '/etc/apt/apt.conf.d/000apt-cacher-ng-proxy'
    state: 'absent'

  - path: '/etc/apt/apt.conf.d/00apt-proxy'
    state: 'absent'

  - path: '/etc/modprobe.d/blacklist-ansible-kernel_module-role.conf'
    state: 'absent'
  - path: '/etc/modprobe.d/options-ansible-kernel_module-role.conf'
    state: 'absent'
  - path: '/etc/modules-load.d/ansible-kernel_module-role.conf'
    state: 'absent'

  - path: '/etc/sysctl.d/10-debops_sysctl.conf'
    state: 'absent'
```

So we could just provide a role similar to `debops.resources` which only cares about deleting files and ship it with a preset of `absent` definitions. This does not need to be defined by default.

Edit: Alternative name: `debops.debops_legacy`. I guess we should prefer this.

Related to: https://github.com/debops/debops/pull/229, https://github.com/debops/debops/pull/249
