### ISSUE TITLE
Support for Certbot  installation

### ISSUE THREAD

**Issue by ced455** [debops/debops#2533]
Hello DebOps team,

I am using Debian 12 and trying to use the Ansible role `pki` with the dns-ovh plugin for Certbot. However, the version of Certbot preinstalled on Debian 12 is 2.1.0, which does not include the fix I need for the dns-ovh plugin to work correctly. The fix was applied in Certbot version 2.7.2, as noted here: [Certbot 2.7.2 release](https://github.com/certbot/certbot/releases/tag/v2.7.2).

Could you kindly advise if there is a way to install or manage Certbot version 2.7.2 (or higher) using DebOps? If not, is there a recommended approach for handling this in conjunction with the DebOps pki role?

Thank you .

**Comment by prahal** [comment]
I see no backports for Debian stable bookworm for certbot. So I bet your best bet is to do the same as https://docs.debops.org/en/stable-3.2/admin-guide/local-apt-repository.html, ie do a local build of certbot >= 2.7.2, setup debops.repropro and host your local certbot backport to your reprepro apt server (and have it added to your host apt sources).
Or have someone cook a PR to do all that in debops like is currently done for ruby and golang.

**Comment by pedrolucasbp** [comment]
I managed to do this. I created a Python venv for the certbot installation and a symbolic link to point the certbot command  on the system to that installation.

If you choose a certbot plugin that is in the Debops PKI pki_acme_type supported list, then you have to take care of the packages that will be installed, otherwise the role will override the symbolic link and you'll get the certbot version from deb packages. 

Here follow a little tutorial: 
 - create under group_vars a folder to a group that will hold the configurations, for example: pki_acme_tld
 - create a file to hold a debops.resources configuration, like that:   
    file: resources_certbot.yml 
```yaml
---
resources__group_paths:
  - path: '/usr/bin/certbot'
    src:  '/usr/local/lib/certbot-venv/bin/certbot'
    state: 'link'
    force: 'true'

resources__group_pip:
  - virtualenv: '/usr/local/lib/certbot-venv'
    name:
      - 'acme>=3.0.0'
      - 'certbot>=3.0.0'
      - 'certbot-dns-ovh' # This is a example!
      - 'setuptools'
      - 'requests'
      - 'mock'
      - 'requests-mock'
```  
 - create a file to disable the packages installation by the debops.pki role: 
   file: pki_packages.yml  
```yaml
---
pki_acme_packages: []
```  
 - run debops.resources and debops.pki roles to configure all needed:   
```bash
debops run service/resources service/pki -l pki.host.example.net
```  
After that, you'll get a clean custom certbot installation. But there is a bug in the pki-realm script and certbot will not work correctly. I've PR (#2570) to fix this bug.
