### ISSUE TITLE
lvm role is harmful and can break bookworm installations and lvm state

### ISSUE THREAD

**Issue by seven-beep** [debops/debops#2581]
Hello,

After using lvm role to add a thin volume on a bare-metal, the root volume is not recognized anymore at next reboot and booting drop me into a initramfs shell.

Moreover after booting into a livecd to inspect the state of lvm, I cannot anymore activate the root volume, leading for me to a dead end and a re-installation of the machine.

As the server is bare-metal with encrypted disk, I could not iterate fast enough to provide much more information than it is the lvm role that is responsible for this. I will eventually setup a virtual machine to investigate further in the future.

The disk layout before using lvm:

````
NAME                      MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
nvme0n1                   259:0    0 476.9G  0 disk  
├─nvme0n1p1               259:1    0   254M  0 part  /boot/efi
├─nvme0n1p2               259:2    0     1G  0 part  /boot
└─nvme0n1p3               259:3    0 475.7G  0 part  
  └─nvme0n1p3_crypt       254:0    0 475.7G  0 crypt 
    ├─crypt-root          254:1    0    10G  0 lvm   /
    ├─crypt-swap          254:2    0     4G  0 lvm   [SWAP]
    ├─crypt-var           254:3    0     5G  0 lvm   /var
    ├─crypt-var_log       254:4    0     5G  0 lvm   /var/log
    ├─crypt-var_log_audit 254:5    0     5G  0 lvm   /var/log/audit
    ├─crypt-var_tmp       254:6    0     5G  0 lvm   /var/tmp
    └─crypt-home          254:7    0     2G  0 lvm   /home
````

**Comment by seven-beep** [comment]
For reference here is the variables I used.

``` yaml
Remove unnecessary devices and add nvme.
lvm__devices_filter:
  - 'a|sd.*|'
  - 'a|nvme.*|'
  - 'r|.*|'
lvm__devices_global_filter: "{{ lvm__devices_filter }}"
lvm__global_use_lvmetad: false

# Standard LVM layout was defined at installation time.  I use the extra space
# as a big thin volume to be used by kvm as a directory pool.
lvm__thin_pools:
  - vg: 'crypt'
    thinpool: "pve"
    size: "400g"
    opts: "--poolmetadatasize 2g"

lvm__logical_volumes:
  - lv: 'srv'
    vg: 'crypt'
    thinpool: 'pve'
    size: '400g'
    mount: '/srv/'
    state: 'present'
    fs_type: 'ext4'
    fs_opts: '-m 0'
```
