### ISSUE TITLE
apt_preferences: default pin archive name invalid

### ISSUE THREAD

**Issue by laikq** [debops/debops#2584]
I want the package `cockpit` and its dependencies to be installed from backports. In the playbook:

```yaml
  vars:
    apt_preferences__list:
      - package: "cockpit*"
    apt_install_packages:
      - cockpit
    apt_install__state: latest
  roles:
    - role: debops.debops.apt
    - role: debops.debops.apt_preferences
    - role: debops.debops.apt_install
```

This yields an entry in `/etc/apt/preferences.d`:

```
Explanation: Reason not specified
Package: cockpit*
Pin: release a=bookworm-backports
Pin-Priority: 500
```

However, this does not change behavior of apt, as the archive name[^1] is `stable-backports`, not `bookworm-backports`. This contradicts the documentation for `apt_preferences__list[x].pin`, which states

> Custom pin definition. If this variable is undefined, the debops.apt_preferences role will automatically configure selected packages with preference for a backported version.

**Expected behavior:** Leaving `pin` undefined should result in a line `Pin: release a=stable-backports` or other in the `.pref`-file.

**Workaround:** Set `pin` explicitly, e.g.

```yaml
  vars:
    apt_preferences__list:
      - package: "cockpit*"
        pin: "release a=stable-backports"
```

**Context:**
- debops version 3.2.4
- ansible core version 2.18.3
- python version 3.11.2

[^1]: defined in release file `/var/lib/apt/lists/deb.debian.org_debian_dists_bookworm-backports_InRelease`, line `Suite: stable-backports`
