### ISSUE TITLE
Make DBNAMES and DBEXCLUDE Configurable in autopostgresqlbackup

### ISSUE THREAD

**Issue by ced455** [debops/debops#2588]
### Description:

Currently, the Ansible role `postgresql_server` includes the `autopostgresqlbackup` script, which by default sets `DBNAMES="all"` and `DBEXCLUDE=""` in the `autopostgresqlbackup.j2` template.

I would like to request that either `DBNAMES` or `DBEXCLUDE` be made configurable, allowing users to specify which databases to include or exclude from the backup process.

### Example:

```yaml
# defaults/main.yml
postgresql_server_autopostgresqlbackup_dbnames: "all"
postgresql_server_autopostgresqlbackup_dbexclude: ""
```

```jinja
# templates/autopostgresqlbackup.j2
{% if postgresql_server_autopostgresqlbackup_dbnames == "all" %}
DBNAMES="{{ postgresql_server_autopostgresqlbackup_dbnames }}"
DBEXCLUDE="{{ postgresql_server_autopostgresqlbackup_dbexclude }}"
{% else %}
DBNAMES="{{ postgresql_server_autopostgresqlbackup_dbnames }}"
DBEXCLUDE=""
{% endif %}
```

Thank you
