### ISSUE TITLE
enable persistent systemd journal

### ISSUE THREAD

**Issue by jankatins** [debops/debops#260]
For that to happen either the `/var/log/journal` directory has to exist (with the default debian systemd packages) or `Storage=persistent` has to go into a conf file (in `/etc/systemd/journal.conf.d/whatever.conf`). It would also be nice to have a setting for the size of the journal.

**Comment by drybjed** [comment]
You can create the directory using `debops.resources`:
```yaml
resources__paths:
  - name: '/var/log/journal'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0750'
```
You could also create the configuration with the same role.

I'm not sure if restart/reload of `journald` is needed to take effect.

Since Debian Stretch uses `rsyslog` for persistent log files by default, I'm not sure if essentially duplicating the functionality with persistent journal by default is necessary. On the other hand, since you are using Debian Sid, do you know if there are plans to drop `rsyslog` in Buster?
