### ISSUE TITLE
debops.sysctrl failes because applying kernel parameters doesn't work

### ISSUE THREAD

**Issue by jankowa** [debops/debops#29]
Applying debops.sysctrl fails on lxc-hosts (on debian stretch) because the role tries to apply the kernel parameter for shared memory:

```yml
- name: Apply kernel parameters if they were modified
  command: '{{ "sysctl --system"
               if (sysctl__register_system.stdout != "")
               else ("sysctl -e -p " + sysctl__config_file) }}'
  when: sysctl__register_config|changed
```

This fails because of:
```
sysctl -e -p /etc/sysctl.d/10-debops_sysctl.conf 
sysctl: setting key "kernel.shmall": read-only filesystem
sysctl: setting key "kernel.shmmax": read-only filesystem
```
We could disable either the shared memory configuration or avoid to apply the kernel parameters during runtime. Does this make sense?

```yml
diff --git a/ansible/roles/debops.sysctl/tasks/main.yml b/ansible/roles/debops.sysctl/tasks/main.yml
index 684c3253..44346581 100644
--- a/ansible/roles/debops.sysctl/tasks/main.yml
+++ b/ansible/roles/debops.sysctl/tasks/main.yml
@@ -28,7 +28,7 @@
   command: '{{ "sysctl --system"
                if (sysctl__register_system.stdout != "")
                else ("sysctl -e -p " + sysctl__config_file) }}'
-  when: sysctl__register_config|changed
+  when: sysctl__register_config|changed and ( ansible_virtualization_type not in [ "lxc", "openvz" ]
```
