### ISSUE TITLE
Error using debops.postfix

### ISSUE THREAD

**Issue by computerlyrik** [debops/debops#376]
I got an error using the postfix-role within debops.mono:

```
TASK [debops.postfix : Generate Postfix 'main.cf' configuration] ***************************************************************************
fatal: [myhost.example.com]: FAILED! => {"changed": false, "msg": "AnsibleError: An unhandled exception occurred while templating '{{ lookup(\"template\", \"lookup/postfix__init_maincf.j2\") }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({% set postfix__tpl_init_maincf = [] %}\n{% for entry in postfix__combined_maincf %}\n{%   if 'section' not in entry.keys() %}\n{%     set entry_name = (entry.name | d(entry.keys()[0])) %}\n{%     if entry_name is search('_sasl_') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'auth'}) %}\n{%     elif entry_name.startswith('smtpd_tls_') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'smtpd-tls'}) %}\n{%     elif entry_name.startswith('smtp_tls_') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'smtp-tls'}) %}\n{%     elif entry_name.startswith('lmtp_tls_') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'lmtp-tls'}) %}\n{%     elif entry_name.startswith('virtual_') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'virtual'}) %}\n{%     elif entry_name.startswith('postscreen_') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'postscreen'}) %}\n{%     elif entry_name.startswith('anvil_') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'limit'}) %}\n{%     elif entry_name.endswith('_limit') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'limit'}) %}\n{%     elif entry_name.endswith('_canonical_maps') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'route'}) %}\n{%     elif entry_name in [ 'canonical_maps', 'relay_domains', 'local_recipient_maps', 'relay_recipient_maps', 'transport_maps' ] %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'route'}) %}\n{%     elif entry_name in [ 'smtpd_milters', 'non_smtpd_milters', 'milter_mail_macros', 'header_checks', 'body_checks', 'content_filter' ] %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'filter'}) %}\n{%     elif entry_name in [ 'smtpd_client_event_limit_exceptions', 'smtpd_error_sleep_time' ] %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'limit'}) %}\n{%     elif entry_name in [ 'smtpd_sender_login_maps' ] %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'auth'}) %}\n{%     endif %}\n{%   endif %}\n{% endfor %}\n{{ postfix__tpl_init_maincf }}\n): expected string or bytes-like object"}
```

**expected string or bytes-like object**

ENV:
```
ansible --version                                                            :(
ansible 2.5.5
  config file = /.../ansible.cfg
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]
```

**Comment by drybjed** [comment]
Did you set any `postfix__*` variables in the inventory? Are you using a custom Ansible playbook with this role? Can you show it?

**Comment by computerlyrik** [comment]
The variables you requested
```
- name: Setting up mailserver
  hosts: mailservers
  become: yes
  roles:
    - name: debops.postfix/env
      tags: [ 'role::postfix', 'role::secret', 'role::ferm' ]

    - name: debops.secret
      tags: [ 'role::secret', 'role::postfix' ]
      secret__directories:
        - '{{ postfix__secret__directories }}'

    - name: debops.postfix
      tags: [ 'role::postfix' ]
      vars:
        postfix__maincf:
          - virtual_mailbox_domains: mydomain.com
          - mydestination: mail.mydomain.com, localhost.mydomain.com, localhost, anotherdomain.de
          - virtual_alias_maps: hash:/etc/postfix/virtual_alias_maps
          - virtual_mailbox_domains: mydomain.com
          - virtual_mailbox_maps: mysql:/etc/postfix/virtual_mailbox_maps.cf
          - virtual_transport: lmtp:127.0.0.1:2003
          - smtpd_sasl_auth_enable: 'yes'
          - smtpd_tls_cert_file: /etc/ssl/kopano/ssl.cert
          - smtpd_tls_key_file: /etc/ssl/kopano/ssl.key
          - smtpd_use_tls: 'yes'
        postfix__tls_cert_file: /etc/ssl/kopano/ssl.cert
        postfix__tls_key_file:  /etc/ssl/kopano/ssl.key
```


there is another role at the end of the playbook, but it should not matter.
It generates the ```virtual_alias_maps``` and the ```virtual_mailbox_maps```

**Comment by drybjed** [comment]
You should explicitly quote things in YAML, and mark them as lists, otherwise they can be interpreted incorrectly. This should make things work:
```
      vars:
        postfix__maincf:
          - virtual_mailbox_domains: [ 'mydomain.com' ]
          - mydestination: [ 'mail.mydomain.com', 'localhost.mydomain.com', 'localhost', 'anotherdomain.de' ]
          - virtual_alias_maps: [ 'hash:/etc/postfix/virtual_alias_maps' ]
          - virtual_mailbox_domains: [ 'mydomain.com' ]
          - virtual_mailbox_maps: [ 'mysql:/etc/postfix/virtual_mailbox_maps.cf' ]
          - virtual_transport: 'lmtp:127.0.0.1:2003'
          - smtpd_sasl_auth_enable: True
          - smtpd_tls_cert_file: '/etc/ssl/kopano/ssl.cert'
          - smtpd_tls_key_file: '/etc/ssl/kopano/ssl.key'
          - smtpd_use_tls: True
        postfix__tls_cert_file: '/etc/ssl/kopano/ssl.cert'
        postfix__tls_key_file:  '/etc/ssl/kopano/ssl.key'
```
Role interpretes values differently depending on if they are strings or lists. This is explained at length [in the documentation](https://docs.debops.org/en/master/ansible/roles/debops.postfix/defaults-maincf.html).

**Comment by computerlyrik** [comment]
Tried exactly as you proposed - but did not work. Same error.

**Comment by computerlyrik** [comment]
Tracked the error down to this line:

```{% set postfix__tpl_maincf = ((postfix__init_maincf + postfix__combined_maincf) | parse_kv_config) %}```

**Comment by computerlyrik** [comment]
```
- name: debug1
  debug:
    var: postfix__init_maincf
```
fails with the same error

**Comment by drybjed** [comment]
I executed the playbook you prodived earlier on one of my hosts and it works fine. I think that this might be related to something else in your environment, maybe DNS configuration on the host?

The `postfix__init_maincf` variable is templated, check its contents with this task:
```
- template:
    src: 'lookup/postfix__init_maincf.j2'
    dest: '/tmp/debug-init'
```
You will either get a templated file with some JSON/YAML data, or a proper error message from the Ansible `template` module which will tell you what might be wrong.

**Comment by computerlyrik** [comment]
When executing the proposed task:
```
TASK [debops.postfix : template] ***********************************************************************************************************
fatal: [mydomain.com]: FAILED! => {"changed": false, "msg": "AnsibleError: Unexpected templating type error occurred on ({% set postfix__tpl_init_maincf = [] %}\n{% for entry in postfix__combined_maincf %}\n{%   if 'section' not in entry.keys() %}\n{%     set entry_name = (entry.name | d(entry.keys()[0])) %}\n{%     if entry_name is search('_sasl_') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'auth'}) %}\n{%     elif entry_name.startswith('smtpd_tls_') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'smtpd-tls'}) %}\n{%     elif entry_name.startswith('smtp_tls_') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'smtp-tls'}) %}\n{%     elif entry_name.startswith('lmtp_tls_') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'lmtp-tls'}) %}\n{%     elif entry_name.startswith('virtual_') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'virtual'}) %}\n{%     elif entry_name.startswith('postscreen_') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'postscreen'}) %}\n{%     elif entry_name.startswith('anvil_') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'limit'}) %}\n{%     elif entry_name.endswith('_limit') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'limit'}) %}\n{%     elif entry_name.endswith('_canonical_maps') %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'route'}) %}\n{%     elif entry_name in [ 'canonical_maps', 'relay_domains', 'local_recipient_maps', 'relay_recipient_maps', 'transport_maps' ] %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'route'}) %}\n{%     elif entry_name in [ 'smtpd_milters', 'non_smtpd_milters', 'milter_mail_macros', 'header_checks', 'body_checks', 'content_filter' ] %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'filter'}) %}\n{%     elif entry_name in [ 'smtpd_client_event_limit_exceptions', 'smtpd_error_sleep_time' ] %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'limit'}) %}\n{%     elif entry_name in [ 'smtpd_sender_login_maps' ] %}\n{%       set _ = postfix__tpl_init_maincf.append({'name': entry_name, 'state': 'init', 'section': 'auth'}) %}\n{%     endif %}\n{%   endif %}\n{% endfor %}\n{{ postfix__tpl_init_maincf }}\n): expected string or bytes-like object"}
```

**Comment by drybjed** [comment]
What do you get when you run the task:
```
- debug: var=postfix__combined_maincf
```
This variable [is a list of multiple variables](https://github.com/debops/debops/blob/master/ansible/roles/debops.postfix/defaults/main.yml#L746-L753), you could check each one this way until you find a faulty one.

**Comment by computerlyrik** [comment]
Having the following:
```
- name: debug0
  debug:
    var: postfix__combined_maincf

- name: debug1
  debug:
    var: postfix__init_maincf
```

First one works, second one fails with the above error. So it is in the init_maincf template?

**Comment by computerlyrik** [comment]
There is no "name","section","value" model on the ```mydestination``` list.

**Comment by computerlyrik** [comment]
in the "combined" ALL of my set variables are appended - but without the "name","section","value" model - is this why it fails?

**Comment by drybjed** [comment]
If you remove the `mydestination` parameter from your configuration, does the role pass? The `mydestination` list is defined [here](https://github.com/debops/debops/blob/master/ansible/roles/debops.postfix/defaults/main.yml#L372-L382), what's the value of `postfix__fqdn`?

**Comment by drybjed** [comment]
The `postfix__init_maincf` is essentially an initialization list for different postfix configuration options that parses raw `postfix__*_maincf` parameters and defines the base sections for them. Are all of the list elements in `postfix__combined_maincf` YAML dictionaries? Can you show the value of `postfix__combined_maincf` you have in that debug task?

**Comment by drybjed** [comment]
I guess that the template needs to check if a given list element examined by it is a `mapping` type and otherwise skip it. That should probably fix the issue, but it would be nice to have a test case first.

**Comment by computerlyrik** [comment]
It is just the vars getting appended without the name,section,value model.

e.g. excerp from ```postfix__combined_maincf```
```
        {
            "virtual_mailbox_maps": [
                "mysql:/etc/postfix/virtual_mailbox_maps.cf"
            ]
        },
        {
            "virtual_transport": "lmtp:127.0.0.1:2003"
        },
        {
            "smtpd_sasl_auth_enable": true
        },
        {
            "smtpd_tls_cert_file": "/etc/ssl/kopano/ssl.cert"
        },
        {
            "smtpd_tls_key_file": "/etc/ssl/kopano/ssl.key"
        },
        {
            "smtpd_use_tls": true
        }
```
These are exacty my variables set.
this fails when parsing ```postfix__init_maincf``` by the j2-template

**Comment by computerlyrik** [comment]
The upper part of ```postfix_combined_maincf``` reads like
```
        {
            "comment": "TLS parameters",
            "name": "smtpd_tls_cert_file",
            "section": "base",
            "value": "/etc/ssl/kopano/ssl.cert"
        },
        {
            "name": "smtpd_tls_key_file",
            "section": "base",
            "value": "/etc/ssl/kopano/ssl.key"
        },
        {
            "name": "smtpd_use_tls",
            "section": "base",
            "value": true
        },
        {
            "name": "smtpd_tls_session_cache_database",
            "section": "base",
            "value": "btree:${data_directory}/smtpd_scache"
        },
        {
            "name": "smtp_tls_session_cache_database",
            "section": "base",
            "value": "btree:${data_directory}/smtp_scache"
        },
```

**Comment by drybjed** [comment]
You said excerpt... Can you paste the whole thing? The variables shown look OK to me, this might be something not apparent to you but apparent to me.

**Comment by computerlyrik** [comment]
```postfix__init_maincf``` tries to parse it with ```{%     set entry_name = (entry.name | d(entry.keys()[0])) %}```
There is no name, i think this is why it fails.

**Comment by drybjed** [comment]
If there's no name, the template will try and extract it from the dictionary key. I think that one of the elements is not a YAML dictionary but something else, and the template fails in this place because of that.

**Comment by computerlyrik** [comment]
So you are the expert, this is the whole ```postfix__combined_maincf``` as you requested:

```yaml
    "postfix__combined_maincf": [
        {
            "comment": "Debian specific:  Specifying a file name will cause the first\nline of that file to be used as the name.  The Debian default\nis /etc/mailname.\n",
            "name": "myorigin_example",
            "option": "myorigin",
            "section": "base",
            "state": "comment",
            "value": "/etc/mailname"
        },
        {
            "name": "smtpd_banner",
            "section": "base",
            "value": "$myhostname ESMTP $mail_name (Debian/GNU)"
        },
        {
            "name": "biff",
            "section": "base",
            "value": false
        },
        {
            "comment": "appending .domain is the MUA's job.",
            "name": "append_dot_mydomain",
            "section": "base",
            "value": false
        },
        {
            "comment": "Uncomment the next line to generate \"delayed mail\" warnings",
            "name": "delay_warning_time",
            "section": "base",
            "state": "comment",
            "value": "4h"
        },
        {
            "name": "readme_directory",
            "section": "base",
            "value": false
        },
        {
            "comment": "See http://www.postfix.org/COMPATIBILITY_README.html -- default to 2 on\nfresh installs.\n",
            "name": "compatibility_level",
            "section": "base",
            "state": "present",
            "value": 2
        },
        {
            "comment": "TLS parameters",
            "name": "smtpd_tls_cert_file",
            "section": "base",
            "value": "/etc/ssl/kopano/ssl.cert"
        },
        {
            "name": "smtpd_tls_key_file",
            "section": "base",
            "value": "/etc/ssl/kopano/ssl.key"
        },
        {
            "name": "smtpd_use_tls",
            "section": "base",
            "value": true
        },
        {
            "name": "smtpd_tls_session_cache_database",
            "section": "base",
            "value": "btree:${data_directory}/smtpd_scache"
        },
        {
            "name": "smtp_tls_session_cache_database",
            "section": "base",
            "value": "btree:${data_directory}/smtp_scache"
        },
        {
            "comment": "See /usr/share/doc/postfix/TLS_README.gz in the postfix-doc package for\ninformation on enabling SSL in the smtp client.\n",
            "name": "smtp_tls_client_comment",
            "section": "base",
            "state": "hidden"
        },
        {
            "name": "smtpd_relay_restrictions",
            "section": "base",
            "state": "present",
            "value": [
                {
                    "name": "permit_mynetworks",
                    "weight": -300
                },
                {
                    "name": "permit_sasl_authenticated",
                    "weight": -200
                },
                {
                    "name": "defer_unauth_destination",
                    "weight": -100
                }
            ]
        },
        {
            "name": "myhostname",
            "section": "base",
            "value": "mail.mydomain.com"
        },
        {
            "name": "alias_maps",
            "section": "base",
            "value": [
                "hash:/etc/aliases"
            ]
        },
        {
            "name": "alias_database",
            "section": "base",
            "value": [
                "hash:/etc/aliases"
            ]
        },
        {
            "name": "myorigin",
            "section": "base",
            "value": "/etc/mailname"
        },
        {
            "name": "mydestination",
            "section": "base",
            "value": [
                "mail.mydomain.com",
                {
                    "name": "localhost.mydomain.com",
                    "weight": 190
                },
                {
                    "name": "localhost",
                    "weight": 200
                }
            ]
        },
        {
            "name": "relayhost",
            "section": "base",
            "value": ""
        },
        {
            "name": "mynetworks",
            "section": "base",
            "value": [
                {
                    "name": "127.0.0.0/8",
                    "weight": 100
                },
                {
                    "name": "::ffff:127.0.0.0/104",
                    "weight": 100
                },
                {
                    "name": "::1/128",
                    "weight": 100
                }
            ]
        },
        {
            "name": "mailbox_size_limit",
            "section": "base",
            "value": 0
        },
        {
            "name": "recipient_delimiter",
            "section": "base",
            "value": "+"
        },
        {
            "name": "inet_interfaces",
            "section": "base",
            "value": "all"
        },
        {
            "name": "inet_protocols",
            "section": "base",
            "state": "ignore",
            "value": "all"
        },
        {
            "name": "html_directory",
            "section": "base",
            "value": false
        },
        {
            "name": "smtpd_banner",
            "value": "$myhostname ESMTP"
        },
        {
            "name": "enable_long_queue_ids",
            "section": "base",
            "state": "present",
            "value": true
        },
        {
            "name": "smtp_tls_client_comment",
            "state": "absent"
        },
        {
            "name": "smtpd_use_tls",
            "section": "smtpd-tls",
            "weight": -500
        },
        {
            "comment": "",
            "name": "smtpd_tls_cert_file",
            "section": "smtpd-tls"
        },
        {
            "name": "smtpd_tls_key_file",
            "section": "smtpd-tls"
        },
        {
            "name": "smtpd_tls_CAfile",
            "section": "smtpd-tls",
            "value": "/etc/ssl/certs/ca-certificates.crt"
        },
        {
            "name": "smtp_tls_CAfile",
            "section": "smtp-tls",
            "value": "/etc/ssl/certs/ca-certificates.crt"
        },
        {
            "name": "lmtp_tls_CAfile",
            "section": "lmtp-tls",
            "value": "/etc/ssl/certs/ca-certificates.crt"
        },
        {
            "name": "smtpd_tls_session_cache_database",
            "section": "smtpd-tls"
        },
        {
            "name": "smtp_tls_session_cache_database",
            "section": "smtp-tls"
        },
        {
            "name": "lmtp_tls_session_cache_database",
            "section": "lmtp-tls",
            "value": "btree:${data_directory}/lmtp_scache"
        },
        {
            "name": "smtpd_tls_dh1024_param_file",
            "section": "smtpd-tls",
            "state": "ignore",
            "value": ""
        },
        {
            "name": "smtpd_tls_dh512_param_file",
            "section": "smtpd-tls",
            "state": "ignore",
            "value": ""
        },
        {
            "name": "smtpd_tls_loglevel",
            "section": "smtpd-tls",
            "value": 1
        },
        {
            "name": "smtp_tls_loglevel",
            "section": "smtp-tls",
            "value": 1
        },
        {
            "name": "lmtp_tls_loglevel",
            "section": "lmtp-tls",
            "value": 1
        },
        {
            "name": "smtpd_tls_security_level",
            "section": "smtpd-tls",
            "value": "may",
            "weight": -500
        },
        {
            "name": "smtp_tls_security_level",
            "section": "smtp-tls",
            "value": "may",
            "weight": -500
        },
        {
            "name": "lmtp_tls_security_level",
            "section": "lmtp-tls",
            "value": "may",
            "weight": -500
        },
        {
            "name": "smtpd_tls_auth_only",
            "section": "smtpd-tls",
            "value": true
        },
        {
            "name": "smtpd_tls_protocols",
            "section": "smtpd-tls",
            "value": [
                "!SSLv2",
                "!SSLv3",
                "!TLSv1",
                "TLSv1.1",
                "TLSv1.2"
            ]
        },
        {
            "name": "smtp_tls_protocols",
            "section": "smtp-tls",
            "value": [
                "!SSLv2",
                "!SSLv3",
                "!TLSv1",
                "TLSv1.1",
                "TLSv1.2"
            ]
        },
        {
            "name": "lmtp_tls_protocols",
            "section": "lmtp-tls",
            "value": [
                "!SSLv2",
                "!SSLv3",
                "!TLSv1",
                "TLSv1.1",
                "TLSv1.2"
            ]
        },
        {
            "name": "smtpd_tls_mandatory_protocols",
            "section": "smtpd-tls",
            "value": [
                "!SSLv2",
                "!SSLv3",
                "!TLSv1",
                "TLSv1.1",
                "TLSv1.2"
            ]
        },
        {
            "name": "smtp_tls_mandatory_protocols",
            "section": "smtp-tls",
            "value": [
                "!SSLv2",
                "!SSLv3",
                "!TLSv1",
                "TLSv1.1",
                "TLSv1.2"
            ]
        },
        {
            "name": "lmtp_tls_mandatory_protocols",
            "section": "lmtp-tls",
            "value": [
                "!SSLv2",
                "!SSLv3",
                "!TLSv1",
                "TLSv1.1",
                "TLSv1.2"
            ]
        },
        {
            "name": "smtpd_tls_ciphers",
            "section": "smtpd-tls",
            "value": "high"
        },
        {
            "name": "smtp_tls_ciphers",
            "section": "smtp-tls",
            "value": "high"
        },
        {
            "name": "lmtp_tls_ciphers",
            "section": "lmtp-tls",
            "value": "high"
        },
        {
            "name": "smtpd_tls_mandatory_ciphers",
            "section": "smtpd-tls",
            "value": "high"
        },
        {
            "name": "smtp_tls_mandatory_ciphers",
            "section": "smtp-tls",
            "value": "high"
        },
        {
            "name": "lmtp_tls_mandatory_ciphers",
            "section": "lmtp-tls",
            "value": "high"
        },
        {
            "name": "smtpd_tls_exclude_ciphers",
            "section": "smtpd-tls",
            "value": [
                "aNULL",
                "RC4",
                "MD5",
                "DES",
                "3DES",
                "RSA",
                "SHA"
            ]
        },
        {
            "name": "smtp_tls_exclude_ciphers",
            "section": "smtp-tls",
            "value": [
                "aNULL",
                "RC4",
                "MD5",
                "DES",
                "3DES",
                "RSA",
                "SHA"
            ]
        },
        {
            "name": "lmtp_tls_exclude_ciphers",
            "section": "lmtp-tls",
            "value": [
                "aNULL",
                "RC4",
                "MD5",
                "DES",
                "3DES",
                "RSA",
                "SHA"
            ]
        },
        {
            "name": "smtpd_tls_eecdh_grade",
            "section": "smtpd-tls",
            "value": "ultra"
        },
        {
            "name": "smtpd_tls_received_header",
            "section": "smtpd-tls",
            "value": true
        },
        {
            "name": "smtp_tls_note_starttls_offer",
            "section": "smtp-tls",
            "value": true
        },
        {
            "name": "lmtp_tls_note_starttls_offer",
            "section": "lmtp-tls",
            "value": true
        },
        {
            "name": "tls_preempt_cipherlist",
            "section": "tls",
            "value": true
        },
        {
            "name": "tls_ssl_options",
            "section": "tls",
            "state": "present",
            "value": "NO_COMPRESSION"
        },
        {
            "name": "smtpd_helo_required",
            "section": "restrictions",
            "value": true
        },
        {
            "name": "strict_rfc821_envelopes",
            "section": "restrictions",
            "value": true
        },
        {
            "name": "smtpd_reject_unlisted_sender",
            "section": "restrictions",
            "value": true
        },
        {
            "name": "disable_vrfy_command",
            "section": "restrictions",
            "value": true
        },
        {
            "name": "smtpd_client_restrictions",
            "section": "restrictions",
            "separator": true,
            "weight": 10
        },
        {
            "name": "smtpd_helo_restrictions",
            "section": "restrictions",
            "value": [
                {
                    "name": "permit_mynetworks",
                    "weight": -400
                },
                {
                    "name": "reject_invalid_helo_hostname",
                    "weight": -300
                },
                {
                    "name": "reject_non_fqdn_helo_hostname",
                    "weight": -200
                },
                {
                    "name": "reject_unknown_helo_hostname",
                    "weight": -100
                }
            ],
            "weight": 20
        },
        {
            "name": "smtpd_sender_restrictions",
            "section": "restrictions",
            "value": [
                {
                    "name": "reject_non_fqdn_sender",
                    "weight": -200
                },
                {
                    "name": "reject_unknown_sender_domain",
                    "weight": -100
                }
            ],
            "weight": 30
        },
        {
            "copy_id_from": "smtpd_sender_restrictions",
            "name": "smtpd_relay_restrictions",
            "section": "restrictions",
            "state": "present",
            "weight": 40
        },
        {
            "name": "smtpd_recipient_restrictions",
            "section": "restrictions",
            "value": [
                {
                    "name": "reject_non_fqdn_recipient",
                    "weight": -200
                },
                {
                    "name": "reject_unknown_recipient_domain",
                    "weight": -100
                }
            ],
            "weight": 50
        },
        {
            "name": "smtpd_data_restrictions",
            "section": "restrictions",
            "value": [
                {
                    "name": "reject_unauth_pipelining",
                    "weight": -200
                },
                {
                    "name": "reject_multi_recipient_bounce",
                    "weight": -100
                }
            ],
            "weight": 60
        },
        {
            "virtual_mailbox_domains": [
                "mydomain.com"
            ]
        },
        {
            "mydestination": [
                "mail.mydomain.com",
                "localhost.mydomain.com",
                "localhost",
                "anotherdomain.com"
            ]
        },
        {
            "virtual_alias_maps": [
                "hash:/etc/postfix/virtual_alias_maps"
            ]
        },
        {
            "virtual_mailbox_domains": [
                "mydomain.com"
            ]
        },
        {
            "virtual_mailbox_maps": [
                "mysql:/etc/postfix/virtual_mailbox_maps.cf"
            ]
        },
        {
            "virtual_transport": "lmtp:127.0.0.1:2003"
        },
        {
            "smtpd_sasl_auth_enable": true
        },
        {
            "smtpd_tls_cert_file": "/etc/ssl/kopano/ssl.cert"
        },
        {
            "smtpd_tls_key_file": "/etc/ssl/kopano/ssl.key"
        },
        {
            "smtpd_use_tls": true
        }
    ]
}
```

When i am getting this right, this is piped into the ```postfix__init_maincf``` template, right?

**Comment by computerlyrik** [comment]
And as soon as the line 5 ```{%     if entry_name is search('_sasl_') %}``` from ```postfix__init_maincf.j2``` gets called, it fails with the error ```expected string or bytes-like object```

**Comment by drybjed** [comment]
Hmmm, that would suggest that this:
```
        {
            "smtpd_sasl_auth_enable": true
        },
```
might be the source of this issue... That's the only entry with `_sasl_` inside. Curiouser and curiouser. What's your `python-jinja2` version? Do you use a `virtualenv` install, or system-wide?  I guess system-wide, and Python 3.6 from the looks of it.

If you remove `smtpd_sasl_auth_enable` entry from your config, does the role pass?

**Comment by computerlyrik** [comment]
stripped down the role call to 
```
    - name: debops.postfix
      tags: [ 'role::postfix' ]
      vars:
        postfix__maincf:
          - virtual_mailbox_domains: [ 'mydomain.com' ]
```
same error.

I still think ```entry_name``` gets something empty on the set on line 4.

``` community/python-jinja 2.10-1 [installed] ```

```
python --version                                                             :(
Python 3.6.5
```

running an arch linux

**Comment by computerlyrik** [comment]
Btw as soon as i remove ALL variables from the role call, it passes

**Comment by drybjed** [comment]
Hmmm, what if you define the `vars:` section on the playbook level instead of the role level?

**Comment by computerlyrik** [comment]
Nothing there. no vars section on playbook level

**Comment by computerlyrik** [comment]
I tried templating again with 
```
- template:
    src: 'lookup/postfix__init_maincf.j2'
    dest: '/tmp/debug-init'
```

with the follwing change in the template file:
```
{% set postfix__tpl_init_maincf = [] %}
{% for entry in postfix__combined_maincf %}
{%   if 'section' not in entry.keys() %}
{%     set entry_name = (entry.name | d(entry.keys()[0])) %}
{{ entry_name }}
{%   endif %}
{% endfor %}
{{ postfix__tpl_init_maincf }}
```

So it would just put out the ```entry_name```

I am getting the following error:

``` 
TASK [debops.postfix : template] ***********************************************************************************************************
fatal: [mail.mydomain.com]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: dict_keys object has no element 0"}
```

**Comment by drybjed** [comment]
No, I mean what happens when you try this playbook?
```
---

- name: Setting up mailserver
  hosts: karma
  become: yes

  vars:
    postfix__maincf:
      - virtual_mailbox_domains: [ 'mydomain.com' ]
      - mydestination: [ 'mail.mydomain.com', 'localhost.mydomain.com', 'localhost', 'anotherdomain.de' ]
      - virtual_alias_maps: [ 'hash:/etc/postfix/virtual_alias_maps' ]
      - virtual_mailbox_domains: [ 'mydomain.com' ]
      - virtual_mailbox_maps: [ 'mysql:/etc/postfix/virtual_mailbox_maps.cf' ]
      - virtual_transport: 'lmtp:127.0.0.1:2003'
      - smtpd_sasl_auth_enable: True
      - smtpd_tls_cert_file: '/etc/ssl/kopano/ssl.cert'
      - smtpd_tls_key_file: '/etc/ssl/kopano/ssl.key'
      - smtpd_use_tls: True
    postfix__tls_cert_file: '/etc/ssl/kopano/ssl.cert'
    postfix__tls_key_file:  '/etc/ssl/kopano/ssl.key'

  roles:
    - name: debops.postfix/env
      tags: [ 'role::postfix', 'role::secret', 'role::ferm' ]

    - name: debops.secret
      tags: [ 'role::secret', 'role::postfix' ]
      secret__directories:
        - '{{ postfix__secret__directories }}'

    - name: debops.postfix
      tags: [ 'role::postfix' ]
```
