### ISSUE TITLE
[debops.console] Restart systemd fs target for automount points

### ISSUE THREAD

**Issue by gardouille** [debops/debops#404]
If some mount points have the the **x-systemd.automount** option they are correctly set in  **/etc/fstab** by debops.console, but the automount won't work cause it needs to restart the according target : 
``` sh
systemctl restart remote-fs.target
systemctl restart local-fs.target
```

- Sample configuration for NFS : 
``` yaml
console_group_mounts_nfs:
  - name: "/mnt/test"
    src: 'test.mydomain.org.:/mnt/test'
    state: 'present'
    fstype: 'nfs4'
    opts: "defaults,x-systemd.automount,x-systemd.device-timeout=2,x-systemd.idle-timeout=1min,noatime,noauto"
```
- For SSHFS share : 
``` yaml
console_group_mounts:
  - name: /mnt/test.sshfs
    src: 'user@test.mydomain.org:/mnt/test.sshfs'
    fstype: "fuse.sshfs"
    opts: "x-systemd.automount,x-systemd.device-timeout=2,x-systemd.idle-timeout=10min,noatime,noauto,intr,allow_other"
    state: 'present'
```

I guess some new handler with a notify should work. But i am not sure of the filter to use to verify if **x-systemd.automount** (or another one) is set in **item.opts**.
