### ISSUE TITLE
debops.pki changing TLS certificate (pki_realm) from internal to acme

### ISSUE THREAD

**Issue by rei-ifesca** [debops/debops#526]
Hello @drybjed,

it is possible to change the signing CA of an exisitng pki_realm?

Currently I have several pki_realms running on a host, initially all signed with the internal PKI created automagically by debops.pki. So far so good. ACME is enabled, hovewer deactivated on a realm basis.

Now I need to use a valid Let's Encrypt TLS cert for an existing realm, thus I changed the acme iteam of the realm to true. An updated some parameters of the subdomains. This changes are detected by the PKI role, hovewer the role keeps signing the cert request with the internal CA, instead of using tiny-acme. 

  - Is this currently possible?
  - Did I miss something?

It would be nice if you have any hints ;)

Rei

**Comment by drybjed** [comment]
Because you cannot modify existing X.509 certificates, `debops.pki` is not designed to update existing PKI realms. Easiest way to test this is to just remove the realm directory (`/etc/pki/realms/<realm>/`) and re-run the role. If you have ACME support installed, you should get the certificates from Let's Encrypt and they should be automatically enabled.

However, the role should had switched to the ACME certificates if they got acquired, even on existing PKI realm (not the `domain` though, it has ACME support intentionally disabled). Are you sure that `acme-tiny` is installed? Does the host have a public IP address so that Let's Encrypt CA can get to it? Is `debops.nginx` configuration applied so that webserver supports ACME requests?

**Comment by rei-ifesca** [comment]
> Because you cannot modify existing X.509 certificates, `debops.pki` is not designed to update existing PKI realms. 

This would be a nice feaute, just like Let's Encrypt allows you to expand existing TLS certificates.

> Easiest way to test this is to just remove the realm directory (`/etc/pki/realms/<realm>/`) and re-run the role.

Already done this, several times. Even removed any reference to the corresponding realm in the ansible-controller ansible/secret path. I always ended up with a certificate signed from the internal PKI.

> If you have ACME support installed, you should get the certificates from Let's Encrypt and they should be automatically enabled.

I can actually get LE certs, however only for "new configured" domains, not existing ones.

> Are you sure that `acme-tiny` is installed? 

Yes, because I can get on the same host other certificates signed by LE.

> Does the host have a public IP address so that Let's Encrypt CA can get to it? 

Yes, a public reachable IPv4. Firewall ports (80,443) also open. Nginx is also working and able to respond to the LE challenges.

> Is `debops.nginx` configuration applied so that webserver supports ACME requests?

Yes, it's a simple nginx-proxy config. It works for any new realm, For the existing one it just takes the internally signed TLS certs, always, nevertheles of which settings I use or files (e.g. `/etc/pki/realm/<name>`) I delete.

Any Idea? ^^

**Comment by drybjed** [comment]
> This would be a nice feaute, just like Let's Encrypt allows you to expand existing TLS certificates

Perhaps, when the `pki-realm` and `pki-authority` scripts are rewritten in Python, the certificate management could be improved in this direction. That reminds me, @bfabio, any progress with the rewrite? :-)

Without more information it's hard to tell what's really happening... Can you show the configuration of a PKI realm that doesn't work, as well as a PKI realm that does? Ie. the stuff you put in the Ansible inventory to configure them.

Other than that, I suppose that we could arrange an online session via remote desktop, so I could look around your setup, maybe that would point to some clues. But first, show the configs.

**Comment by rei-ifesca** [comment]
> Without more information it's hard to tell what's really happening... Can you show the configuration of a PKI realm that doesn't work, as well as a PKI realm that does? Ie. the stuff you put in the Ansible inventory to configure them.

Inventory: `ansible/inventory/hosts`
```
[debops_all_hosts:children]
hetzner

debops_service_bootstrap:children]
hetzner

[debops_no_common:children]
#empty

[debops_service_core:children]
hetzner

[debops_service_etc_aliases:children]
hetzner

[debops_service_ferm:children]
hetzner

[debops_service_postfix:children]
hetzner

[debops_service_nginx:children]
www.host.hetzner.mydomain.com

[hetzner]
www.host.hetzner.mydomain.com
```

`ansible/inventory/group_vars/pki.yml`
```
pki_acme: True

pki_default_subdomains: []
pki_acme_default_subdomains: []

pki_ca_domain: 'mydomain.com'
pki_ca_organization: 'My Company GmbH'
pki_ca_root_key_size: '8192'
pki_ca_domain_dn: [ 'o={{ pki_ca_organization }}', 'ou=Org CA' ]
pki_ca_service_dn: [ 'o={{ pki_ca_organization }}', 'ou=Internal Services CA' ]

pki_realm_key_size: '4096'

pki_system_ca_certificates_download_all_hosts_force: True

pki_realms:

  - name: '{{ ansible_domain }}'
    acme: False
    subject_alt_names:
      - 'dns:*.{{ ansible_domain }}'

  - name: '{{ ansible_fqdn }}'
    acme: False
    subject_alt_names:
      - 'dns:*.{{ ansible_fqdn }}'
      - 'uri:https://{{ ansible_fqdn }}/'
      - 'IP:127.0.0.1'
      - 'IP:0:0:0:0:0:0:0:1'
      - 'IP:{{ ansible_default_ipv4.address }}'
      - '{{ ("IP:" + ansible_default_ipv6.address
           if (ansible_default_ipv6|d() and ansible_default_ipv6.address|d())) }}'

```

`ansible/inventory/host_vars/www.host.hetzner.mydomain.com.yml`
```
nginx_servers:
  # Working let's encrypt TLS cert
  - name:
      - 'www.mydomain.com'
    enabled: True
    state: 'present'
    type: 'proxy'
    acme: True
    ssl: True
    redirect_to_ssl: True
    auth_basic: True
    # Name of the htpasswd file, based on the name of the virtual_server
    auth_basic_name: 'www.mydomain.com'
    location:
      '/': |
       proxy_pass http://v0113_backend;
       proxy_http_version 1.1;
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       #Forward Websocket (WS://) over Proxy
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "Upgrade";


  - name:
    # With TLS, but signed with internal PKI
      - 'v0.11.3.mydomain.com'
      - 'v0.11.3.mydomain.de'
      - 'v0.11.3.mydomain.net'
    enabled: True
    state: 'present'
    type: 'proxy'
    acme: True
    ssl: True
    redirect_to_ssl: True
    auth_basic: True
    # Name of the htpasswd file, based on the name of the virtual_server
    auth_basic_name: 'www.mydomain.com'
    location:
      '/': |
       proxy_pass http://v0113_backend;
       proxy_http_version 1.1;
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       #Forward Websocket (WS://) over Proxy
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "Upgrade";

  - name:
     # Working let's encrypt TLS cert
      - 'another.mydomain.com'
    enabled: True
    state: 'present'
    type: 'proxy'
    acme: True
    ssl: True
    redirect_to_ssl: True
    auth_basic: True
    # Name of the htpasswd file, based on the name of the virtual_server
    auth_basic_name: 'another.mydomain.com'
    location:
      '/': |
       proxy_pass http://another_backend;
       proxy_http_version 1.1;
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       #Forward Websocket (WS://) over Proxy
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "Upgrade";


nginx_http_extra_options: |
  client_max_body_size 10000m;
nginx_upstreams:
  - name: 'v0113_backend'
    server: '127.0.0.1:8813'
    options: |
         keepalive 32;
  - name: 'another_backend'
    server: '127.0.0.1:2410'
    options: |
         keepalive 32;

nginx_htpasswd:
  # Create specified user accounts for specified virtual_server
  - name: 'www.mydomain.com'
    # List of HTTP Basic Auth accounts for this virtual_server
    users: [ 'alice' ]
    state: 'present'

  - name: 'another.mydomain.com'
    users: [ 'bob' ]
    state: 'present'



pki_host_realms:
    # Working let's encrypt TLS cert
  - name: 'www.mydomain.com'
    acme: True

    # With TLS, but signed with internal PKI
  - name: 'v0.11.3,mydomain.com'
    acme: True

    # Working let's encrypt TLS cert
  - name: 'another.mydomain.com'
    acme: True

```

This are the inventory and group and host variables. It is a copy-paste of the current relevant configuration with sanitized domains. If you need details of the real domains and cert, just send me a PM.

So basically it is just a simple TLS webserver acting as reverse proxy for a backend service.

Initially this domains (`v0.11.3,mydomain.com`, `another,mydomain.com`) were signed by the internal pki and everything worked. Now to make the service publicly availble we need valid TLS certificates. Thus I changed the realm config to `acme: True`. Interestengly it worked with the second but not the first. I just need the single domains, no special subdomains or whatsoever. The aliases in the
`v0.11.3.mydomain.com` virtualhost are not included in the Let's Encrypt cert, because the other alias domains are pointing to another server currently.

**Comment by drybjed** [comment]
```
    # With TLS, but signed with internal PKI
  - name: 'v0.11.3,mydomain.com'
    acme: True
```
Umm, that's not a thing that would work with Let's Encrypt CA, I think... Especially that in the corresponding `nginx` server configuration you are using a dot instead of a comma. Do you even get any signed X.509 certificate in this PKI realm? Can you show the `tree` output of that realm directory?

Man, in your comment after the configs you use a comma and a dot interchangeably in the domain names. You know that the commas are not valid in DNS domain names, right? Just making sure...

**Comment by rei-ifesca** [comment]
The comma is a **typo** while changing the domain names '-_- Just sed'it while reading with a dot ;-)

Just checked my original config again, and the only commas are in the comments. 
The domains are also valid and retrievable over DNS.

Any idea what I am doing wrong?

**Comment by drybjed** [comment]
@rei-ifesca OK then, sorry about that. Is anything being created in the `acme/` directory of that PKI realm? Can you show me the `tree /etc/pki/realm/<v0.11.3.mydomain.com/` output?

**Comment by rei-ifesca** [comment]
> @rei-ifesca Is anything being created in the `acme/` directory of that PKI realm? 

Yes it is. Thank you for the hint. I found there the acme error log describing the error:
`'Error creating new order :: DNS name has too many labels'` and showing a list of domains which was wrongly created due to the fact, that the host fqdn is not the same domain for the TLS cert and the domain is also another one :D

Short: debops.pki is creating an `acme_domains` list with the default settings which result in wrong domains, e.g. "v0.11.3.mydomain.com, v0.11.3,mydomain.com.mydomain.com, v0.11.3.hetzner.mydomain.com".

The fix is simple and gives more control: **define the acme_domains myself**

```
pki_host_realms:
    # Working let's encrypt TLS cert
  - name: 'www.mydomain.com'
    acme: True
    acme_domains:
      - 'www.mydomain.com'
    
    # With TLS, but signed with internal PKI
  - name: 'v0.11.3,mydomain.com'
    acme: True
    acme_domains:
      - 'v0.11.3.mydomain.com'
      - 'www.mydomain.com'
   
    # Working let's encrypt TLS cert
  - name: 'another.mydomain.com'
    acme: True
    acme_domains:
      - 'another.mydomain.com'

```
@drybjed thank you for the hint! :)
