### ISSUE TITLE
debops.nginx as standalone role

### ISSUE THREAD

**Issue by rei-ifesca** [debops/debops#567]
Hi,

Does the debops.nginx role from Galaxy work as a standalone role?

Currently with a simple play it runs but only does some apt stuff. Ferm is disabled.

Based on the official documented play at https://docs.debops.org/en/master/ansible/roles/debops.nginx/getting-started.html#example-playbook I created a play which at the end calls the debops.nginx role in order to create a proxy virtual host including an upstream. 

Nothing fancy. Yet it runs, all green however  the needed nginx config is not created.

In this case it is important not to run debops but ansible-playbook.

FYI the python env is isolated with virtualenv.

Anyone any idea what I am doing wrong.?

**Comment by drybjed** [comment]
Downloading DebOps roles from Ansible Galaxy is broken - the server recognizes them in the monorepo, but the clients (`ansible-galaxy`, `mazer`) don't know how to deal with it and download the entire monorepo instead of a single role. You should either stick to downloading DebOps from GitHub directly, or  make sure that the directory with the roles is in the `roles_path` in `ansible.cfg`.

The `debops.nginx` role should work as standalone. If you show the playbook you are using, and Ansible output, I could tell a bit more about what might be the issue.

**Comment by rei-ifesca** [comment]
Hello,

good to known that the galaxy roles should not be used...

Using your hint with the ``roles_path`` and virtualenv I managed to get the debops.nginx role working :)

The solutions is not just to add ``roles_path`` to ``ansible.cfg`` but also ``lookup_plugins``.

```
## Configure VirtualEnv
virtualenv ~/${VIRTUALENV_NAME}
source ~/${VIRTUALENV_NAME}/bin/activate

# Install needed Ansible/DebOps dependencies
sudo apt-get install \
    python-virtualenv virtualenv build-essential \
    python-dev libffi-dev libssl-dev libsasl2-dev libldap2-dev

pip install --upgrade setuptools ansible~=${ANSIBLE_INSTALL_VERSION} debops~=${DEBOPS_INSTALL_VERSION}

```

And ``ansible.cfg`` contains this:
```
[defaults]

roles_path = ${VIRTUAL_ENV}/lib/python2.7/site-packages/debops/ansible/roles
lookup_plugins = ${VIRTUAL_ENV}/lib/python2.7/site-packages/debops/ansible/playbooks

```

The playbook look like this:
```
---
- name: Deploy 
  hosts: [ 'dev' ]
  tags: [ 'play::deployment' ]
  become: yes
  gather_facts: yes

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:
    - role: deploy
      tags: [ 'role::deploy', 'skip::deploy' ]
      ansible_python_interpreter: '/usr/bin/env docker-python'

    - role: debops.nginx
      tags: [ 'role::nginx', 'skip::nginx' ]
      ansible_python_interpreter: /usr/bin/python
      nginx__dependent_servers:
        - '{{ deploy__nginx__dependent_servers }}'
      nginx__dependent_upstreams:
        - '{{ deploy__nginx__dependent_upstreams }}'

```
