### ISSUE TITLE
Bootstrap: Is it possible to specify a specific ssh key rather than default id_rsa?

### ISSUE THREAD

**Issue by zenflip** [debops/debops#590]
I was reading this paragraph:

```
Ansible commands are executed on the Ansible Controller from unprivileged account alice. 
This user has an SSH key pair stored in ~/.ssh/id_rsa or has its SSH key available in the 
SSH Agent. An administrator account with the same name will be created on the remote 
host during the bootstrap process.
```
https://docs.debops.org/en/master/debops-playbooks/guides/getting-started.html?highlight=ansible_ssh_host

I see the default behavior is to use the ~/.ssh/id_rsa however is it possible to override this and specify a specific key e.g. ~/.ssh/ubuntu instead? That way I can share a key among specific hosts and not all of them. And also not share my ~/.ssh/id_rsa if I don't want to. 

I'm also not that clear on why the authorized_keys of both alice@ and root@ contains so many entries, maybe all my keys in .ssh? Shouldn't it just contain the one and also can it be specified exactly?

I'm a bit confused by what is happening basically. Please can you explain or point to the relevant docs which I couldn't find on the first pass.

Also, is there any documentation about what steps bootstrap.yml and common.yml actually do? I find I'm flying a little blind as I don't know what is actually happening on my servers lol.

Many thanks.

-Mike

**Comment by drybjed** [comment]
Sure. The list of SSH public keys added to the `root` and admin accounts by the `debops.bootstrap` role is defined using the `bootstrap__admin_sshkeys` variable:

https://github.com/debops/debops/blob/master/ansible/roles/debops.bootstrap/defaults/main.yml#L129

As you can see, the role first tries to get the list of SSH keys from the SSH agent, and if that doesn't work it will try to get the `~/.ssh/*.pub` keys from your current user directory. You can override this variable in the Ansible inventory and for example, specify different SSH keys for different host groups. Currently the same set of keys is added to all admin accounts and the `root` account, but that will probably change in the future.

As for the steps of different playbooks - you can see in the [`bootstrap.yml`](https://github.com/debops/debops/blob/master/ansible/playbooks/bootstrap.yml) and [`common.yml`](https://github.com/debops/debops/blob/master/ansible/playbooks/common.yml) playbooks which roles are included in them. The playbooks themselves don't perform any tasks, all is done on the role level. You can then check each role that interests you for its tasks and default variables. Most of the roles [are extensively documented](https://docs.debops.org/en/master/ansible/role-index.html#role-index), so it's a good idea to check the documentation included in the project as well.

If you still have any questions, come over to the project's IRC channel, they can then be answered in real time, most of the time. :-)

**Comment by zenflip** [comment]
Again, fantastic response. Thanks.

**Comment by rei-ifesca** [comment]
Hello,

altouht the issue is already closed, I just want to give jm2c:

We have a dict defining a list of ssh keys for each user. Then the bootstrap role takes for each defined (admin) user the list of keys. This enable us to have more tight control on which ssh keys for which user will be set.
With the ``debops.users`` role "normal" users are defined, not necessarily with ssh access.

```yaml

# SSH authentication pub key
# This variable is a dict or lists, with each key beeing the official linux user-login.
# Each user can have multiple SSH pub keys stored, thus increasing the flexibility.
ssh_auth_keys:
  ansible:
    - "ssh-ed25519 aaaabbbbccccddd...."
    - "ssh-rsa aaaaaadddddddffffff..."
  alice:
    - "ssh-ed25519 aaaabbbbccccddd...."
    - "ssh-rsa aaaaaadddddddffffff..."
  bob:
    - "ssh-ed25519 aaaabbbbccccddd...."
    - "ssh-rsa aaaaaadddddddffffff..."


# SuperAdmin/Root user after 'root'.
# We define the user ansible as the first global admin user. This user should only be used by ansible.
bootstrap__admin_sshkeys: "{{ ssh_auth_keys.ansible }}"
bootstrap__admin_default_users: 
  - name: 'ansible'
    state: 'present'

# Additional admin users, ussually humans, which will be configured on each ansible host.
# See https://docs.debops.org/en/latest/ansible/roles/debops.bootstrap/defaults-detailed.html#bootstrap-ref-admin-users
bootstrap__admin_users:
  - name: "alice"
    state: 'present'
    system: False
    sshkeys: "{{ ssh_auth_keys.alice}}"
  - name: "bob"
    state: 'present'
    system: False
    sshkeys: "{{ ssh_auth_keys.bob}}"


users__group_accounts:
  - name: 'carl'
    state: 'present'
    group: 'myservice'
    groups:
      - 'myservice'
      - 'docker'
      - 'sshusers'
    append: True
    generate_ssh_key: False
    sshkeys: []
    sshkeys_exclusive: True

  - name: 'alice'
    state: 'present'
    groups:
      - 'myservice'
      - 'docker'
      - 'sshusers'
    append: True

  - name: 'gitlabrunner'
    state: 'present'
    group: 'gitlabrunner'
    groups:
      - 'gitlabrunner'
      - 'myservice'
      - 'docker'
      - 'sshusers'
    append: False
    generate_ssh_key: False
    sshkeys: "{{ ssh_auth_keys.gitlabrunner }}"
    sshkeys_exclusive: True
```

**Comment by zenflip** [comment]
Thanks for above rei-ifesca. To clarify.

Presumably the yml you quoted above is something that would go in say an `users.yml` file where `ssh_auth_keys` is a configurable variable like `bootstrap__admin_sshkeys`? 

So you'd end up with something like:

project1/ansible/inventory/group_vars/users.yml
```
---
ssh_auth_keys:
  ansible:
    - "ssh-rsa ..."
  ubuntu:
    - "ssh-rsa ..."
  someuser:
    - "ssh-rsa ..."
bootstrap__admin_sshkeys: "{{ ssh_auth_keys.ansible }}"
bootstrap__admin_default_users: 
  - name: 'ansible'
    state: 'present'
bootstrap__admin_users:
  - name: "someuser"
    state: 'present'
    system: False
    sshkeys: "{{ ssh_auth_keys.someuser}}"
...
```

After Bootstrap (using above .yml) I've noticed that I have one authorized key in `root/authorized_keys` for the `ansible` user. I also have an admin user set up as me who is a member of an admin group and that same user has an authorized_keys file with two keys in it: one for `someuser` and one for `ansible`. 
I also have a system `ansible` system user in `/var/local/ansible` and that has an `authorized/keys file` with one key for the `ansible` user.

That seems better.
