### ISSUE TITLE
Bootstrap: Privilege issues with ansible_user. Needs more clarity. 

### ISSUE THREAD

**Issue by zenflip** [debops/debops#591]
On this page:
https://docs.debops.org/en/latest/debops-playbooks/guides/getting-started.html

Bootstrapping debops with an ansible_user doesn't seem to work as expected. I would have thought I need to specify `ansible_user=ansible` (as below) however debops bombs out if I do that saying it's expecting root. 
`Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?\r\n`

project1/ansible/inventory/hosts
```
[debops_all_hosts]
ubuntu1    
    ansible_ssh_host=server.example.com ansible_user=ansible 
    ansible_ssh_private_key_file=~/.ssh/ubuntu
```

The Bootstrap only seems to work if I take the `ansible_user=ansible` out and so the script runs as the current user which presumably `becomes root`?

And then put these in to run the `common` roles after the `ansible` admin user has been created by the bootstrap process. 

```
[debops_all_hosts:vars]
ansible_user=ansible
ansible_become=yes
```

**Comment by drybjed** [comment]
If you put `ansible_user` variable in the inventory, it will take precedence over `ansible --user` command line parameter. In that case bootstrapping the host through a `root` account without `sudo` available becomes impossible. This will have to be explained better in the documentation.

I think that in the near future, the tasks and variables related to admin accounts will be moved to a separate role, similar to `debops.root_account`, included both in common playbook and in bootstrap playbook. This should allow for more robust admin account management.

**Comment by zenflip** [comment]
As per the other thread I [posted](https://github.com/debops/debops/issues/590), I ended up creating this:

group_vars/all/users.yml

```
---
ssh_auth_keys:
  adminuser:
    - "ssh-rsa ..."
  developer:
    - "ssh-rsa ..."
bootstrap__admin_sshkeys: "{{ ssh_auth_keys.adminuser }}"
bootstrap__admin_default_users: 
  - name: 'adminuser'
    state: 'present'
bootstrap__admin_users:
  - name: 'developer'
    state: 'present'
    system: False
    sshkeys: "{{ ssh_auth_keys.developer}}"
...
```

That seems to work well.

This way adminuser (example name) handles all the DebOps actions.
