### ISSUE TITLE
debops.postfix/env role fails with 'dict object' has no attribute 'iteritems'

### ISSUE THREAD

**Issue by singuliere** [debops/debops#614]
Using python 3.7 and ansible 2.7.5, the following playbook:

```
- name: install and configure postfix relay
  hosts: 'postfix-host'
  become: true

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'
  roles:
    - role: debops.postfix/env
```

fails with

```
    PLAY [install and configure postfix relay] *************************************
    
    TASK [Gathering Facts] *********************************************************
    ok: [postfix-host]
    
    TASK [debops.postfix/env : Check if the dependent master.cf configuration exists] ***
    skipping: [postfix-host]
    
    TASK [debops.postfix/env : Load the dependent master.cf configuration from Ansible Controller] ***
    skipping: [postfix-host]
    
    TASK [debops.postfix/env : Prepare Postfix environment] ************************
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using
`result|version_compare` use `result is version_compare`. This feature will be
removed in version 2.9. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
    fatal: [postfix-host]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'iteritems'\n\nThe error appears to have been in '/home/singuliere/software/enough/infrastructure/molecule/postfix/roles/debops.postfix/env/tasks/main.yml': line 24, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Prepare Postfix environment\n  ^ here\n"}
```
