### ISSUE TITLE
/.local/share/debops/ are not created at pip install

### ISSUE THREAD

**Issue by bbichero** [debops/debops#628]
I'm using Debian stretch (9.5), I installed all the recommends packages and then install debops with `pip`.
Directory `~/.local/share/debops/` wasn't created, Iike the closed issue https://github.com/debops/debops/issues/226#issue-305608236 I must run the `debops-update` to have this folder.

I work also on MacOS Sierra, and the directory was created (with pip install) in `/Users/bbichero/Library/Application Support/debops`, why not install is it user the same directory as on Linux system ?
Ansible doesn't like space in path (`\` doesn't work)

**Comment by drybjed** [comment]
The `debops` Python package contains its own set of the playbooks and roles released with a given version. The `debops` script knows where to look for them and should work out of the box. You shouldn't have to download the repository separately if you want to use the specific version. I'll add a note about this in the installation documentation.

As for the installation path on macOS, the default on Linux comes from `$XDG_DATA_HOME` variable which is not supported on macOS, therefore [the default directory is changed](https://github.com/debops/debops/commit/e0a949f118d67699abce5c11939ebdb657d91c06). I remember the issue with spaces in paths and Ansible not working, is that still relevant today? Did you try on current stable Ansible?

In any case, you can download the DebOps monorepo by specifying the path for it:
```
debops-update ~/.local/share/debops
```
That should clone the repository in the above directory.

**Comment by bbichero** [comment]
Sorry I didn't provide all the informations, I wanted to include custom roles / playbooks inside `playbooks/site.yml` like the documentation said.

But in the configuration the path file `site.yml` was in  `'{{ lookup("ENV", "HOME") + "/.local/share/debops/debops/ansible/playbooks/site.yml" }}'`
This is why I wanted that `.local/share` directory.

Thank you for the information about the path dir under macOS.
I have installed ansible with debops (`pip install --user debops[ansible]`), version 2.7.6
I re-run the test under macOS Sierra : 
> sites.yml
```
---
- import_playbook: "/Library/Application\ Support/debops/debops/ansible/playbooks/site.yml"
- import_playbook: firewall.yml
```

And the error is : 

**ERROR! Unable to retrieve file contents**
**Could not find or access '/Library/Application' on the Ansible Controller.**
**If you are using a module and expect the file to exist on the remote, see the remote_src option**

**Comment by drybjed** [comment]
This seems like `copy` module error to me... I doubt that this is the only line that was returned by Ansible. WIthout the context, especially the task name, it's impossible to tell where the problem is located.

Can you paste the entire run of the playbook and the command you used to execute it?

**Comment by bbichero** [comment]
This is the only error lines that ansible return me ...

I ran :  
`debops -vvv playbooks/sites.yml`

And I got : 
```
Running Ansible playbooks:
playbooks/sites.yml
ansible-playbook 2.7.6
  config file = /Users/bbichero/github/RS-2-repo/debops-env/roger-skyline-2/ansible.cfg
  configured module search path = ['/Users/bbichero/github/RS-2-repo/debops-env/roger-skyline-2/ansible/playbooks/library', '/Users/bbichero/github/RS-2-repo/debops-env/roger-skyline-2/ansible/plugins/library', '/Users/bbichero/github/RS-2-repo/debops-env/roger-skyline-2/ansible/library', '/Users/bbichero/github/RS-2-repo/debops-env/roger-skyline-2/debops/ansible/playbooks/playbooks/library', '/Users/bbichero/github/RS-2-repo/debops-env/roger-skyline-2/debops/ansible/playbooks/library', '/Users/bbichero/github/RS-2-repo/debops-env/roger-skyline-2/debops/ansible/plugins/library', '/Users/bbichero/github/RS-2-repo/debops-env/roger-skyline-2/debops/ansible/library', '/Users/bbichero/Library/Application Support/debops/debops/ansible/playbooks/playbooks/library', '/Users/bbichero/Library/Application Support/debops/debops/ansible/playbooks/library', '/Users/bbichero/Library/Application Support/debops/debops/ansible/plugins/library', '/Users/bbichero/Library/Application Support/debops/debops/ansible/library', '/Users/bbichero/github/RS-2-repo/debops-env/lib/python3.7/site-packages/debops/ansible/library', '/Users/bbichero/github/RS-2-repo/debops-env/lib/python3.7/site-packages/debops/ansible/playbooks/library', '/Users/bbichero/Library/Application Support/debops/debops/ansible/playbooks/library', '/usr/share/ansible/library']
  ansible python module location = /Users/bbichero/github/RS-2-repo/debops-env/lib/python3.7/site-packages/ansible
  executable location = /Users/bbichero/github/RS-2-repo/debops-env/bin/ansible-playbook
  python version = 3.7.2 (default, Jan 14 2019, 11:50:31) [Clang 9.0.0 (clang-900.0.39.2)]
Using /Users/bbichero/github/RS-2-repo/debops-env/roger-skyline-2/ansible.cfg as config file
/Users/bbichero/github/RS-2-repo/debops-env/roger-skyline-2/ansible/inventory/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/Users/bbichero/github/RS-2-repo/debops-env/roger-skyline-2/ansible/inventory/hosts did not meet script requirements, check plugin documentation if this is unexpected
Parsed /Users/bbichero/github/RS-2-repo/debops-env/roger-skyline-2/ansible/inventory/hosts inventory source with ini plugin
ERROR! Unable to retrieve file contents
Could not find or access '/Users/bbichero/Library/Application' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
```

Error just come from [Strategy plugin](https://github.com/ansible/ansible/blob/422604fb3e19b6dc3dce8b943d1f5a3b937a3ac7/lib/ansible/plugins/strategy/__init__.py#L814) where playbook are include.

The new content of `playbook/sites.yml` (If I add \ before the space the result is the same): 
```
---
#- import_playbook: '{{ lookup("ENV", "HOME") + "/.local/share/debops/debops/ansible/playbooks/site.yml" }}'
- import_playbook: "/Users/bbichero/Library/Application Support/debops/debops/ansible/playbooks/site.yml"
- import_playbook: security.yml
```

> playbooks/security.yml
```
---

- name: Security playbook
  hosts: [ "{{ host | default('basic_conf_hosts') }}" ]
  tags: [ 'play::security' ]
  become: true

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: ansible-role-firewall
      tags: [ 'role::firewall', 'skip::firewall' ]

    - role: ansible-role-security
      tags: [ 'role::sshd', 'skip::sshd' ]

    - role: debops.sudo
      tags: [ 'role::sudo', 'skip::sudo' ]

    - role: debops.apt_install
      tags: [ 'role::apt_install', 'skip::apt_install' ]

    - role: debops.users
      tags: [ 'role::users', 'skip::users' ]

    - role: debops.resources
      tags: [ 'role::resources', 'skip::resources' ]
```

The problem come from ansible and not debops, if I ran the command with`ansible-playbook` I got exactly the same output. I will post an issue to ansible.
