### ISSUE TITLE
Issues with debops --tags / --skip-tags

### ISSUE THREAD

**Issue by bbichero** [debops/debops#631]
I have a custom playbook and I want to run a particular role (here there is only one role but the goal is to test how --tags and --skip-tags works)
> ##### playbooks/firewall.yml
```
- name: Manage the your specific setup
  # This is an Ansible inventory file in INI format. You can define a list of
  hosts: [ 'debops_all_hosts' ]

  roles:
    - role: firewall
      tag: [ 'role::firewall' ]
```
After find the empty documentation page about the [CLI arguments ](https://docs.debops.org/en/master/user-guide/debops-cli.html) I figured out that `debops` commands take almost the same arguments as `ansible-playbook`.

After seen issue https://github.com/debops/debops/issues/444 I've try :
`debops --tags role::firewall playbooks/firewall.yml` --> run no role
`debops --skip-tags role::firewall playbooks/firewall.yml` --> run the firewall role

If I replace
`  tag: [ 'role::firewall' ]`
by
`  tag: [ 'firewall' ]`
and I run : 
`debops --skip-tags "firewall" playbooks/firewall.yml`

I got an error :  

**Usage: ansible-playbook [options] playbook.yml [playbook2 ...]**
**ansible-playbook: error: --skip-tags option requires an argument**

But why ? Can you please provide more informations about the CLI ?

Thank you.

**Comment by drybjed** [comment]
Yes, the `debops` command passes its arguments to the `ansible-playbook` command, that's how the `--tags` and `--skip-tags` parameters work.

The tags need to specified in the `tags` list, not `tag`. The correct playbook would be:
```yaml
- name: Manage the your specific setup
  hosts: [ 'debops_all_hosts' ]

  roles:
    - role: firewall
      tags: [ 'role::firewall' ]
```
Then it should work as expected with `--tags` running the role in the speicifed playbook, and `--skip-tags` skipping the role.
