### ISSUE TITLE
[debops.postgresql_server] Fails at "Update default admin password"

### ISSUE THREAD

**Issue by masaoliou** [debops/debops#649]
file "pg-server.yml":

````yaml
---

- name: Manage PostgreSQL server
  hosts: all
  become: True
  roles:
    - role: debops.postgresql_server
      tags: [ 'role::postgresql_server' ]
      postgresql_server__upstream: true
      postgresql_server__auto_backup: false
#      postgresql_server__admin_password: "{{ pg_pass }}"
      postgresql_server__trusted: [ "root", "postgres" ]
      postgresql_server__allow: [ "0.0.0.0/0" ]
      postgresql_server__listen_addresses: [ '*' ]
      postgresql_server__cluster_main:
        name: 'main'
        port: '5432'
        hba:
          - type: 'host'
            database: 'all'
            user: 'all'
            address: [ '0.0.0.0/0' ]
            method: 'md5'
````

run command:

````shell
ansible-playbook pg-server.yml -vvv -u root -i 192.168.1.108, -e pg_pass=123abc -t role::postgresql_server
````

error messages:

    TASK [debops.postgresql_server : Update default admin password] ****************
    task path: /etc/ansible/roles/debops.postgresql_server/tasks/secure_installation.yml:3
    An exception occurred during task execution. The full traceback is:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 98, in run
        item_results = self._run_loop(items)
      File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 281, in _run_loop
        res = self._execute(variables=task_vars)
      File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 443, in _execute
        self._task.post_validate(templar=templar)
      File "/usr/lib/python2.7/dist-packages/ansible/playbook/task.py", line 248, in post_validate
        super(Task, self).post_validate(templar)
      File "/usr/lib/python2.7/dist-packages/ansible/playbook/base.py", line 373, in post_validate
        value = templar.template(getattr(self, name))
      File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 427, in template
        disable_lookups=disable_lookups,
      File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 383, in template
        disable_lookups=disable_lookups,
      File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 583, in do_template
        res = j2_concat(rf)
      File "<template>", line 7, in root
      File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 162, in resolve
        val = super(AnsibleContext, self).resolve(key)
      File "/usr/lib/python2.7/dist-packages/jinja2/runtime.py", line 153, in resolve
        return self.parent[key]
      File "/usr/lib/python2.7/dist-packages/ansible/template/vars.py", line 92, in __getitem__
        raise type(e)(to_native(variable) + ': ' + e.message)
    AttributeError: {{ lookup('password', secret + '/credentials/' + ansible_fqdn + '/postgresql/default/' + postgresql_server__user + '/password length=' + postgresql_server__password_length + ' chars=ascii,digits,.-_~!$&()*+;=') }}: {{ secret__root + "/" + ((secret__levels + "/") if secret__levels else "") + secret__name }}: {{ inventory_dir | realpath }}: 'NoneType' object has no attribute 'startswith'
    fatal: [192.168.1.108]: FAILED! => {
        "failed": true, 
        "msg": "Unexpected failure during module execution.", 
        "stdout": ""
    }

=====

If uncomment the playbook to include this variable:

````yaml
    postgresql_server__admin_password: "{{ pg_pass }}"
````

then I get this error:

    <192.168.1.108> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/cnliou/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.1.108 '/bin/sh -c '"'"'sudo -H -S -n -u postgres /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-rdazpzxrtfvawqsbhmxlxoixveemcdwt; /usr/bin/python /tmp/ansible-tmp-1487766984.54-82653947905827/postgresql_user.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
    <192.168.1.108> ESTABLISH SSH CONNECTION FOR USER: root
    <192.168.1.108> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/cnliou/.ansible/cp/ansible-ssh-%h-%p-%r 192.168.1.108 '/bin/sh -c '"'"'rm -f -r /tmp/ansible-tmp-1487766984.54-82653947905827/ > /dev/null 2>&1 && sleep 0'"'"''
    failed: [192.168.1.108] (item=(censored due to no_log)) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}

Am I doing anything wrong?
Thanks!
