### ISSUE TITLE
[debops.apt_install] Won't remove packages as suggested in examples

### ISSUE THREAD

**Issue by gardouille** [debops/debops#742]
The [apt_install__all_packages](https://docs.debops.org/en/master/ansible/roles/debops.apt_install/defaults-detailed.html#id15) examples suggests it can manage **absent** state. But only **apt_install__state** seems to be applied (cf https://github.com/debops/debops/blob/master/ansible/roles/debops.apt_install/tasks/main.yml#L35) :
``` yaml
- name: Install requested APT packages
  apt:
    name: '{{ item }}'
    state: '{{ apt_install__state }}'
```

Maybe something like : 
``` yaml
- name: Install requested APT packages
  apt:
    name: '{{ item }}'
    state: '{{ item.state | apt_install__state }}'
```
can solve this but i am I'm not really comfortable with lookup and apt_install__all_packages.j2 ^^
