### ISSUE TITLE
gitlab_runner: allow multiple gitlab_runner__token

### ISSUE THREAD

**Issue by drzraf** [debops/debops#864]
Having `gitlab_runner__token` an array would allow to register a runner for multiple project at once otherwise one is reduced to run the same role many times for this sole purpose:
```yaml
- include_role: name=debops.gitlab_runner
  with_items:
    - "{{ all_tokens }}"
  loop_control:
    loop_var: gitlab_runner__token
```

**Comment by drybjed** [comment]
You can specify [multiple runner instances](https://docs.debops.org/en/master/ansible/roles/debops.gitlab_runner/defaults.html#gitlab-runner-instances), each can have its own GitLab CI token. Something like this:
```yaml
gitlab_runner__instances:

  - name: 'docker1'
    executor: 'docker'
    token: 'token1'

  - name: 'docker2'
    executor: 'docker'
    token: 'token2'
```
I don't see how `gitlab_runner__token` being an array would help in this case. That would imply that you are registering the same runner in multiple GitLab CI services. Is this a use case you are looking for?
