### ISSUE TITLE
What exactly does docker_server setup?

### ISSUE THREAD

**Issue by htgoebel** [debops/debops#870]
The description for `debops.docker_server` is quite terse.

I  suggest the following questions to be answered in [docs/ansible/roles/debops.docker_server/introduction.rst](https://github.com/debops/debops/blob/master/docs/ansible/roles/debops.docker_server/introduction.rst).

- What exactly does it set up?
- Is this role required to run docker containers on a debops-managed server?
- Is there some role using this role to be used as an example?

**Comment by drybjed** [comment]
The `debops.docker_server` role sets up the Docker service itself. You can use it to run the Docker Containers on a host. Containers will be managed by the `debops.docker` role, currently in worked on in https://github.com/debops/debops/pull/834. The `debops.docker_server` is not designed to be used as a dependency by other roles, the `debops.docker` role will be (hopefully) designed to support that.

Alternatively, you can write Ansible playbooks with `docker_*` module tasks that set up and tear down the containers, which you can then apply against a host that has the `debops.docker_server` applied.

**Comment by imrejonk** [comment]
I just added support for using the new `debops.docker` role as a dependency in #834 (WIP). Seems to work well enough with a playbook role like this:
```
- role: debops.docker
  tags: [ 'role::docker', 'skip::docker' ]
  docker__dependent_networks:
    - '{{ somerole__docker__dependent_networks }}'
  docker__dependent_registry_accounts:
    - '{{ somerole__docker__dependent_registry_accounts }}'
  docker__dependent_containers:
    - '{{ somerole__docker__dependent_containers }}'
```
